### ISSUE TITLE
Trim video isn't working properly

### ISSUE THREAD

**Issue by deadcoder0904** [alyssaxuu/screenity#1]
Hey, @alyssaxuu I tried `Trim Video` 2-3 times but when I click `Apply` after reducing time, nothing happens. 

Also, the video starts being unresponsive & displays the old time.

For example, I recorded a video until 1:00 & trimmed it from 0:55 to 1:00. And then clicked `Apply`. The timing in Start & End changed perfectly but the video got hanged (if I try to `Play`, nothing happens.. the `Play` button remains as is)

Even after downloading the video, it doesn't show anything. It gets corrupted I think.

**Comment by alyssaxuu** [comment]
Hmm, this is odd - just tried it and indeed there seems to be a glitch, just to confirm the video looks all black?

I'm going to try to identify what's going on to fix it.

**Comment by deadcoder0904** [comment]
> the video looks all black?

yep & the play button doesn't work.

also, it might be helpful to differentiate between trim video's `Apply` & the below one, both look the same so it's kinda confusing but you're the designer 😂🙈

**Comment by alyssaxuu** [comment]
I have disabled trimming the start of a video for now - I realized if you do that it removes the header information of the blob and it won't play. I should be using FFMPEG for this - the only issue is the Js version I am using has some problems with the opus codec from the audio in the Webm recording and it won't work. I should probably look into using some sort of API for this or running my own server somewhere, the only issue is that it's certainly costly and I want to keep it free, I'll try exploring some options...

**Comment by deadcoder0904** [comment]
> it's certainly costly and I want to keep it free

I think you can try vercel.com which offers free personal a/c :)

**Comment by alyssaxuu** [comment]
> > it's certainly costly and I want to keep it free
> 
> I think you can try [vercel.com](https://vercel.com) which offers free personal a/c :)

I believe they have rate limits though, and running FFMPEG would certainly exceed them.

**Comment by vknt** [comment]
> I have disabled trimming the start of a video for now - I realized if you do that it removes the header information of the blob and it won't play.

Could you just always leave the first frame in to preserve the header? At 15-30fps it likely won't be notice-able.

As for the trimming generally I have 2 suggestions:

#### 1. Match "Trim video" to established UX pattern or remove altogether

If it's an operation other than adjusting the start point or end point of the clip, I believe it needs to be called something else like "cut" or "remove", which you already have just below it. Removing something from the end is currently way more intuitive in the "Remove part of video" workflow than in the "Trim video" workflow. The reason to keep Trim is that it's less step to remove something from the beginning and the end. If it's just one side, it's the same amount of steps.

This is what I expect in a trimming experience:

![Trim Start-End](https://user-images.githubusercontent.com/239392/100025377-80443080-2d9d-11eb-8938-4575312bf8d3.png)

 References:
* https://docs.microsoft.com/en-us/stream/portal-edit-trim
* https://support.apple.com/guide/quicktime-player/trim-a-movie-or-clip-qtpf2115f6fd/mac
* https://support.apple.com/en-gb/guide/final-cut-pro/ver9847ec25/10.5/mac/10.15.6

#### 2. Ability to not see the process to stop the recording.

These are seconds that are known not to be valuable. Typically screenrecorders have a keyboard shortcut to stop the recording to avoid these last seconds, another option would be to have ability to automatically trim the seconds between clicking the Screenity icon and Stop Recording.

**Comment by alyssaxuu** [comment]
> > I have disabled trimming the start of a video for now - I realized if you do that it removes the header information of the blob and it won't play.
> 
> Could you just always leave the first frame in to preserve the header? At 15-30fps it likely won't be notice-able.
> 
> As for the trimming generally I have 2 suggestions:
> 
> #### 1. Match "Trim video" to established UX pattern or remove altogether
> If it's an operation other than adjusting the start point or end point of the clip, I believe it needs to be called something else like "cut" or "remove", which you already have just below it. Removing something from the end is currently way more intuitive in the "Remove part of video" workflow than in the "Trim video" workflow. The reason to keep Trim is that it's less step to remove something from the beginning and the end. If it's just one side, it's the same amount of steps.
> 
> This is what I expect in a trimming experience:
> 
> ![Trim Start-End](https://user-images.githubusercontent.com/239392/100025377-80443080-2d9d-11eb-8938-4575312bf8d3.png)
> 
> References:
> 
> * https://docs.microsoft.com/en-us/stream/portal-edit-trim
> * https://support.apple.com/guide/quicktime-player/trim-a-movie-or-clip-qtpf2115f6fd/mac
> * https://support.apple.com/en-gb/guide/final-cut-pro/ver9847ec25/10.5/mac/10.15.6
> 
> #### 2. Ability to not see the process to stop the recording.
> These are seconds that are known not to be valuable. Typically screenrecorders have a keyboard shortcut to stop the recording to avoid these last seconds, another option would be to have ability to automatically trim the seconds between clicking the Screenity icon and Stop Recording.

The trimming controls are temporary until I find a solution. Keeping the first frame isn't possible because the video is recorded in blobs which can be up to a second long, which are certainly noticeable.

As per #2, there are already keyboard shortcuts in place (look in the popup menu) to start recording, stop, and more. I don't want to automatically remove the end of the recording because some people might still be talking until they click the pause/stop button.

I just need to figure out how to use FFMPEG in a server while somehow not being too expensive, that would solve the trimming problem.

**Comment by vknt** [comment]
> The trimming controls are temporary until I find a solution. Keeping the first frame isn't possible because the video is recorded in blobs which can be up to a second long, which are certainly noticeable.

Understood! For me personally it's not very important to be solved functionality wise: using the countdown it's easy to prepare a perfect start..

> As per your second point, there are already keyboard shortcuts in place (look in the popup menu) to start recording, stop, and more.

Found them, thx!

**Comment by megaroeny** [comment]
> Hmm, this is odd - just tried it and indeed there seems to be a glitch, just to confirm the video looks all black?
> 
> I'm going to try to identify what's going on to fix it.

For me in Edge, what happens is the video becomes super short. For example, if I trim a few seconds off the start and the original total was 11 seconds in length, after applying the "remove part of video", it becomes a mere 2 second clip. 😢 

No worries though, I am trimming it directly in Windows afterward.

**Comment by rahulbansal16** [comment]
> . Keeping the first frame isn't possible because the video is recorded in blobs which can be up to a second long, which are certainly noticeable.

I have actually tried keeping the first few seconds of the video and removing the middle part. The video file created in that way does not play properly. It only plays for the first few seconds only.

I feel one way is to create the Matroska container directly using the stream.

**Comment by alyssaxuu** [comment]
Fixed in the new MV3 version.
