### ISSUE TITLE
Desktop limitations (Windows 10)?

### ISSUE THREAD

**Issue by megaroeny** [alyssaxuu/screenity#10]
1. I'm on Windows 10, and I'm not seeing a recorded camera circle if I choose the **Desktop - Application Window** option (that is not a browser application window). Guessing this is a limitation? If so, I wouldn't allow the camera to be recorded for the **Desktop - Application Window** option.

2. I also can't use the annotations tool, if I start a Desktop recording, on an application window that's not the browser. Again, maybe a limitation of a browser extension? If so, don't offer the option for Desktop recording.

Awesome start, and really looking forward to using it more for work! 😄

**Comment by alyssaxuu** [comment]
Indeed, as a Chrome Extension it is impossible to go beyond the browser, so controls and the camera can only be injected inside Chrome. This is the same behaviour that every other screen recorder extension has, they all offer desktop recording despite being unable to show UI controls outside of the browser. I'm keeping it as it's certainly handy for people regardless :)

**Comment by megaroeny** [comment]
Okay, no worries. Thanks!
