### ISSUE TITLE
Turn on screen recording using website

### ISSUE THREAD

**Issue by hanumanjiblog** [alyssaxuu/screenity#101]
If any user want to record then they click on third party website record button they can start recording, please make this that will increase usage of this extension. 

feature name is- "Call From Your Own WebSite"

**Comment by alyssaxuu** [comment]
That's a good idea, I have plans to do something like this. Not a high priority atm though.

**Comment by alyssaxuu** [comment]
Closing this as I don't really want to allow Screenity to be triggered externally by another website for a variety of reasons (privacy, scope of the product, etc). I might have a separate SDK not connected to the extension in the future, but it would work quite differently.
