### ISSUE TITLE
Cannot use erase tool to delete arrows and text boxes

### ISSUE THREAD

**Issue by the-phuctran** [alyssaxuu/screenity#104]
Cannot use erase tool to delete arrows and text boxes, should have the undo tool for this. Also if the erase tool erase a whole line in a single action it would be great.

**Comment by alyssaxuu** [comment]
I could implement that, maybe having to click on top of the arrow or textbox, and ignoring it while dragging through (to be able to erase drawings). I'll see what I can do.

**Comment by alyssaxuu** [comment]
Working now on the newest MV3 version.
