### ISSUE TITLE
code fix recommendation -> should be changed from "max" to "60"

### ISSUE THREAD

**Issue by amirdresler** [alyssaxuu/screenity#105]
https://github.com/alyssaxuu/screenity/blob/935ea64aab0fa16d1c7e603117e9f118e529e234/js/popup.js#L294

Popup click move from 60 to 30 but not back.
this is due the value of "max" that should be "60"

**Comment by alyssaxuu** [comment]
Yeah, probably should be the case. I think I set it to max to work on all sorts of systems, but if I clearly state 60 / 30 it should be precise indeed. Will update soon.

**Comment by alyssaxuu** [comment]
Fixed in the latest version.
