### ISSUE TITLE
duration shown in videoeditor UI is less than the actual video length

### ISSUE THREAD

**Issue by prashant-shahi** [alyssaxuu/screenity#106]
It shows video length as `00:01:22` in the Video Editor UI.
However, the actual video length is `00:01:58`.

**Comment by alyssaxuu** [comment]
Yeah, there's certainly some duration formats, has to do with broken metadata when generating the webm video. Might be able to fix it soon though!

**Comment by alyssaxuu** [comment]
Should be working now on the newest MV3 version.
