### ISSUE TITLE
ffmpeg.js load failed for GIF output

### ISSUE THREAD

**Issue by lokpro** [alyssaxuu/screenity#108]
Hi,
on videoeditor.html, when I choose "GIF" and click "download", the following error is thrown, thanks.

same on Chrome Version 95.0.4638.54 (Official Build) (64-bit) and 
Vivaldi | 4.3.2439.44 (Stable channel) (64-bit)
Revision | 6baf3843e8bd4863b130aa31a9a16030b4372afd
OS | Windows 7 Service Pack 1 (Build 7601.24494)
JavaScript | V8 9.4.146.21

Refused to load the script 'chrome-extension://kbbdabhdfibnancpjfhlkhafgdilcnji/js/libraries/ffmpeg.js' because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

![image](https://user-images.githubusercontent.com/2010297/138069110-478ecbda-8791-45f1-8c24-8dee2f40e96a.png)

**Comment by jtandy123** [comment]
> Ah ok I got it, needs to be under web_accessible_resources. Will update now.

the problem still exist
![image](https://user-images.githubusercontent.com/7404106/142986592-3c9b6d2d-8df1-401b-9441-3893d8afa035.png)
Google Chrome | 96.0.4664.55 (Official Build) (x86_64)
Screenity: 2.7.6
