### ISSUE TITLE
[Feature] Have user be able to set starting position of camera 

### ISSUE THREAD

**Issue by taewookim** [alyssaxuu/screenity#110]
Often times, top left (where rounded video bubble is) is where company's logo is .. and when i try to move the camera bubble, click event gets fired to the logo and page redirects... and its quite frustrating.

**Comment by alyssaxuu** [comment]
Hmm, how does the click event fire though if the camera is over it? Are you dragging it from an edge instead of grabbing it from the center? I could look into adding an option for it, but I just don't know where I could put it in really.

**Comment by alyssaxuu** [comment]
Should be working now on the new MV3 version.
