### ISSUE TITLE
Hello! At the moment of saving, disappeared. Where can I find this file? Luciano

### ISSUE THREAD

**Issue by lucianogonzagavanderley** [alyssaxuu/screenity#111]
Hi! I don't know how to navigate your page. I'll try telling my problem: yesterday, 06nov21, at 10:15 am, I started recording a very important class on meet.google.com/aqt-xwre-pkg through its Screenity , Google Chgrome extension. At the moment of saving, disappeared. Where can I find this file?

**Comment by alyssaxuu** [comment]
If you closed the final page (or Chrome itself) after making the recording, it should have automatically been saved in your downloads folder.
