### ISSUE TITLE
Not working on Linux/Gnome

### ISSUE THREAD

**Issue by corsali-albert** [alyssaxuu/screenity#112]
The extension no longer works on Linux using Gnome. I use pipewire and wayland, either of which might be causing issues. Screenshot below for the behavior (clicking around to different tabs changes the text of the "Loading..." button to "start recording" and darkens the blue color, but clicking it still does not result in recording).
![Screenshot from 2021-11-29 13-12-53](https://user-images.githubusercontent.com/83140544/143938083-07236419-fa73-4665-b97a-6a198a396f2f.png)

**Comment by alyssaxuu** [comment]
That is unfortunate. I can't really look into it sadly as I don't use that OS - you could try looking into any console errors you're getting to try to see if I can fix the issue.

**Comment by jsaponara** [comment]
running ubuntu 20.04 and gnome 3.36.8, screenity works for me using chrome 97.0 but not using brave 1.28.105 [brave is another chromium-based browser].  in the console, i get no errors but the same warning [see below] from both browsers.  so try another browser.  but screenity can work in linux.

warning is: DevTools failed to load source map: Could not load content for chrome-extension://.../js/libraries/pickr.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by GonzaloSP** [comment]
@corsali-albert most of the current screen recorders do not work with wayland. If you change to X11 it will work.

**Comment by alyssaxuu** [comment]
Is it working now with the new MV3 version?

**Comment by jsaponara** [comment]
Way better!  Brave 1.61 [the latest] installs and runs screenity great, tho the download fails with a "Network error".  Let me know where to look for more detail if that would help.

**Comment by alyssaxuu** [comment]
> Way better! Brave 1.61 [the latest] installs and runs screenity great, tho the download fails with a "Network error". Let me know where to look for more detail if that would help.

Ah hmm that's weird. I think it must be related to the fact the editor runs in a sanbox, so FFMPEG can run to encode and edit the video. The downloads are done with the Chrome API from the page directly, but I could add a fallback to download from the service worker in the background instead, which shouldn't be blocked by the browser. Will try to get it in ASAP.

**Comment by alyssaxuu** [comment]
> Way better! Brave 1.61 [the latest] installs and runs screenity great, tho the download fails with a "Network error". Let me know where to look for more detail if that would help.

I was able to fix the bug for Brave, it should be working now in version 3.0.4. I've published it to the Chrome Store and it should be available there in a few hours.

**Comment by jsaponara** [comment]
screenity 3.0.4 works beautifully in brave 1.61, thanks!
