### ISSUE TITLE
Missing translations - Italian

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#116]
Hello, 

Operating system: Windows, Mac OS
Browser: Version 97.0.4692.71

Steps: 

1. Change browser language to Italian
2. Start recording
3. Stop recording

You will see that the "Download" button is not translated: 
![image](https://user-images.githubusercontent.com/51126637/149613059-7e71acad-ccb4-4174-985d-b916bca07df0.png)

**Comment by netlopa** [comment]
@huciaa @alyssaxuu I am Italian: the translation of "Download" is "Scarica".

Anyway it's accepted both "Download" and "Scarica" (we commonly use the English word)

**Comment by alyssaxuu** [comment]
Should be ok in the new MV3 version.
