### ISSUE TITLE
Missing translations - Tamil

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#117]
Hello,

Operating system: Windows, Mac OS
Browser: Version 97.0.4692.71

Steps:

Change browser language to Tamil

1. Start recording
2. Click on the setting button on the toolbar
3. You will see that the translation is missing.
![image](https://user-images.githubusercontent.com/51126637/149613112-9f6e60e6-c7c4-4fed-8b02-f2d4fca2b09e.png)

**Comment by alyssaxuu** [comment]
Added in the latest version.
