### ISSUE TITLE
"Only Camera" option is not working

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#118]
Operating system: Mac OS
Browser: Version 97.0.4692.71

Steps:

1. Start recording with these settings: 
![image](https://user-images.githubusercontent.com/51126637/149613164-bd8510cc-e016-4294-8ae6-b256b9fc4c30.png)

2. Stop recording
3. The recording is missing
![image](https://user-images.githubusercontent.com/51126637/149613210-8498d64e-89f9-4be0-be7c-3cb48d5a57d1.png)

**Comment by alyssaxuu** [comment]
I will look into this, seems to be having some issues indeed.

**Comment by kihlaj** [comment]
For "Camera only", after completing video, you don't get redirected to videoeditor.html and what is recorded is lost. It happens around half the time. This issue might be related to this bug

**Comment by alyssaxuu** [comment]
Fixed in the latest version.
