### ISSUE TITLE
"Tab only" records the screen with poor quality

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#119]
Hello,

Operating system: Windows, Mac OS
Browser: Version 96.0.4664.110 x64

Steps:

1. Start recording with these settings
![image](https://user-images.githubusercontent.com/51126637/149613263-79865d7f-9fde-4cfd-a4fc-8c6241b3e91b.png)
2. Stop recording
3. 
![image](https://user-images.githubusercontent.com/51126637/149613386-89dac6ef-d859-4c9e-bcbf-315ec1e92b2d.png)

**Comment by alyssaxuu** [comment]
That's very unusual. Does it happen every time? Have you changed any FPS / quality options in the popup? You could try also changing the size of the Chrome window to see if that changes anything, it could be causing issues.

**Comment by thejohnha** [comment]
May be unrelated, but after testing Tab vs Window vs Screen recording, the Tab recording is almost unusably slow. Window and Screen recording are performant. Thanks for your awesome work.

**Comment by alyssaxuu** [comment]
Should be fixed on the new MV3 version
