### ISSUE TITLE
Remove part of video not working fine

### ISSUE THREAD

**Issue by roloxls** [alyssaxuu/screenity#12]
. My original video es 14 seconds long
. Then I set "Start" at 00:02 and "End" at 00:14 (I asume this is the part of the video I want to keep)
. I press "Apply" (I should get a 12:00 seconds video)
. But I get 02:00 second video! (Ok, I understand i must indicate part of the video to cut, not to keep)

I press "Reset changes" and I try again:

. I set "Start" at 00:00 and "End" at 00:02
. I press "Apply"
. I get a black video and play button do not play anything

Please check!

**Comment by alyssaxuu** [comment]
Yes, the first behaviour is the expected one. The second one is a current issue I am having which is mentioned here #1, the video headers get removed if you delete the beginning of the video rendering it unplayable. I am trying to find a way to solve this, but so far like I explained there it seems like it would require to use some sort of API or service to trim the video in the backend, which would cost money (& the extension is free, so can't really afford it). I'll close this issue as it's the same one as #1 basically.
