### ISSUE TITLE
Microphone stays active even when it's disabled 

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#120]
Operating system: Mac OS
Browser: Version 97.0.4692.71

Steps:

1. Start recording with these settings:
![image](https://user-images.githubusercontent.com/51126637/149613547-67092226-6e80-429b-a7df-ab5b3ffc8b23.png)
2. Stop recording 

Expected result: 
The sound from the microphone is not being recorded 

Result: 
The sound from the microphone is being recorded.

**Comment by alyssaxuu** [comment]
I can't reproduce this one. Have you clicked on the microphone button after starting the recording? That would toggle it and cause it to be enabled.

**Comment by huciaa** [comment]
Hi, 
Correct, I have enabled the microphone during the recording. 
I was under impression that the microphone will remain disabled.

**Comment by alyssaxuu** [comment]
Yeah, I made it this way so it can be used on-demand.
