### ISSUE TITLE
Camera stays active even when it's disabled

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#121]
Operating system: Mac OS
Browser: Version 97.0.4692.71

Steps:

1. Start recording with these settings:
![image](https://user-images.githubusercontent.com/51126637/149613607-3284cc45-9cf3-4ac8-a450-8a2d5fe9bb20.png)

2. Enable camera
![image](https://user-images.githubusercontent.com/51126637/149613681-d80bc529-38bf-4494-9205-5c7a346236c1.png)

3. Stop recording

Expected result:
The camera is not recorded

Result: 
The image from the camera is being recorded

**Comment by alyssaxuu** [comment]
That is the expected behavior. You can start off with the camera disabled, then click on the camera icon to enable it at some point during the recording. This allows users to only use the camera when they need it.
