### ISSUE TITLE
Cursor is being recorded when recording in "Desktop" mode

### ISSUE THREAD

**Issue by huciaa** [alyssaxuu/screenity#122]
Operating system: Windows, Mac OS
Browser: 97.0.4692.71 x64

Steps:

1. Start a recording with these settings:

![image](https://user-images.githubusercontent.com/51126637/149613755-df6ac2f1-ae1d-4299-9df1-fe37026e4e28.png)

2. Select the hide option 
![image](https://user-images.githubusercontent.com/51126637/149613827-366b2760-3224-4ca2-8cb6-1fe9ff02b831.png)

3. Stop recording 

Expected result:
The cursor is not being recorded

Result: 
The cursor is being recorded

**Comment by alyssaxuu** [comment]
Yeah, the cursor cannot be hidden outside the context of Chrome, since it's a Chrome extension. Nothing I can do about that sadly.
