### ISSUE TITLE
Video editing issues

### ISSUE THREAD

**Issue by Klepert** [alyssaxuu/screenity#123]
Windows 10
chrome 96.0.4664.110 x 64

Record in webm: if you cut front part of video it corupts it so it turns black and cannot be run.

Record in gif: cannot be downloaded
Shortening  the video for less than half of the video causes video to corrupt.
If you cut beggining of the video it turns black and unable to run.
If you cut out the middle of the video it doesn't change lenght, in the part that was supposed to be cut out it is corrupted.
If you cut out back of vid if it is more than couple seconds then it turns black and unable to run.

**Comment by alyssaxuu** [comment]
Yeah, these are known issues. See #1. The GIF issue will be fixed in the new version.
