### ISSUE TITLE
Unable to move the slider

### ISSUE THREAD

**Issue by codeasashu** [alyssaxuu/screenity#124]
While the rercording finish, and I am at the editing page, I am unable to fast forward the video using slider. On inspecting, I am seeing following errors:

```js
Uncaught Error: noUiSlider (14.6.2): 'range' 'min' and 'max' cannot be equal.
    at Object.b [as t] (nouislider.min.js:2:6279)
    at nouislider.min.js:2:11375
    at Array.forEach (<anonymous>)
    at vt (nouislider.min.js:2:11242)
    at Object.updateOptions (nouislider.min.js:2:24611)
    at m (videoeditor.js:1:405)
    at videoeditor.js:1:2657
    at HTMLDivElement.<anonymous> (videoeditor.js:1:2662)
    at HTMLDivElement.dispatch (jquery-3.5.1.min.js:2:43090)
    at HTMLDivElement.v.handle (jquery-3.5.1.min.js:2:41074)
```

**Comment by alyssaxuu** [comment]
That's odd - does this still happen with the latest version?

**Comment by arianbessonart** [comment]
> That's odd - does this still happen with the latest version?

Yes, it's still happening.

**Comment by Kabishou** [comment]
we meet too in lastet version

**Comment by arianbessonart** [comment]
@alyssaxuu I tracked down the commit who broke things and it was [this one](https://github.com/alyssaxuu/screenity/commit/5272fded700a566d00ea5a7339cbab3a177e318d).
There were a lot of changes in that commit, so isn't so easy to find the specific error without having the knowledge of the codebase, however, I'll try to check it out.

**Comment by Krazybug** [comment]
Hi, nothing new on this issue ? The issue is the same in VLC after that the video is downloaded locally

**Comment by alyssaxuu** [comment]
Updated in the new MV3 version.
