### ISSUE TITLE
Not generating anything

### ISSUE THREAD

**Issue by codeagencybe** [alyssaxuu/screenity#126]
Hello

I have installed the latest version, everything went fine. 
I can start/stop recordings, but when I finish one, it doesn't generate anything. 

Even a short clip of eg 10 seconds, I tried waiting for an hour, nothing comes. 
No error either so I can't pinpoint to anything. 
All permissions have been given to the extension so I would expect this to run flawlessly. 
I'm using Edge browser if that matters. 

Screenshot what I get after I click "confirm" the recording below. 
Everything works as expected, except nothing in my output file....

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/7568546/150802350-6d0c5a15-0dd8-49a7-bf37-4a71fea76f7d.png">

**Comment by alyssaxuu** [comment]
Hmm, that's odd. Which version of Screenity are you using - directly from GitHub, the Chrome Store, or from the Microsoft Edge Store?

**Comment by MaxwellADN** [comment]
I got the same issue. It works every other time. I get the tool directement from chrome store. So I'm not sure if I'm capturing anything sometimes

**Comment by dokata99** [comment]
I get the same issue. It's comming only when you reset extension and you start recording full desktop without mic... if you start record tab only and then desktop there is no problem.

**Comment by dokata99** [comment]
go to background.js on row 149 and comment it. I think this will fix it. 
![image](https://user-images.githubusercontent.com/72043010/159682092-e3df72dc-6b98-4836-ae87-472039b61c2a.png)

**Comment by dokata99** [comment]
@alyssaxuu I think this fixed the issue on full screen recording. Don't use disconnect(destination)! Use the **micstream** prop (enable) set it to false/true for mute/unmute. Hope this helps.
![image](https://user-images.githubusercontent.com/72043010/160145423-66603fcd-e079-4738-b2f0-e5c49cc2172f.png)

**Comment by alyssaxuu** [comment]
Should be working now in the new MV3 version.
