### ISSUE TITLE
screenity now also saving file to desktop automatically?

### ISSUE THREAD

**Issue by aminco-edw** [alyssaxuu/screenity#127]
Since about 1-2 weeks ago, screenity started saving the screen recording video to my local computer, which seems odd.

First, it's a bit intrusive, since the file save window/dialog can show up on the actual recording itself.

Second, most of the time, I'm directly saving the files to Google Drive, so I have to delete the file on my computer and it's taking up extra space.

Is this a bug? Or a feature? If it's a feature, can it be turned off?

**Comment by alyssaxuu** [comment]
It is a feature, people have been asking me about ways to recover the file if something happened while recording, so I implemented this which asynchronously saves the file. I suppose I could make it be able to be turned off, although this ensures that very long recordings don't exceed the max memory available, as they write to disk.

**Comment by aminco-edw** [comment]
That makes sense. I wonder if the save file dialog could kick in *before* it actually starts recording.

Otherwise, if you're recording the entire desktop, the first few seconds of the recording will always show the save file dialog, if that makes sense.

**Comment by alyssaxuu** [comment]
Updated in the new MV3 version.
