### ISSUE TITLE
Edit local webm file & Input time

### ISSUE THREAD

**Issue by hustuhao** [alyssaxuu/screenity#129]
Thank you for developing the project screenity, I really like it.

I feel it could be better to allow users to choose the webm file in the local hard disk so that the user can edit the webm created by Screenity later.(Sometimes I want to edit the output webm file later, or edit some other webm files)

When I trim the video, I find it is hard to set  the start and  the end to time point that I want.So I feel it could be better to input the start and end time by using my keyboard.

Thank you for reading this!

**Comment by alyssaxuu** [comment]
Should be fixed in the new MV3 version.
