### ISSUE TITLE
javascript function to start and stop recording.

### ISSUE THREAD

**Issue by aamir2007** [alyssaxuu/screenity#131]
Can I have JavaScript function that I can use to start and stop the recording from a web page when this extension is installed? And on stop it return the local file url of recorded video. It will be awesome feature for web developers to implement on screen recording.

Regards,
Aamir

**Comment by alyssaxuu** [comment]
I might create a separate version for this purpose, where Screenity can be implemented inside a website (separate to the extension) using a SDK. I don't think it's a good idea for a website to be able to control the Screenity extension for another user automatically through a javascript function.

**Comment by alyssaxuu** [comment]
Closing as I won't implement it for controlling the extension.
