### ISSUE TITLE
Doesn't record when switching between tabs.

### ISSUE THREAD

**Issue by GonzaloSP** [alyssaxuu/screenity#135]
Hi Alyssa,

I love the extension. 
I cannot find a way to record when switching between tabs. 
It always records in the tab where I start the recording but it doesn't show the other tabs. 
Is the Desktop mode currently working?

Thanks

**Comment by alyssaxuu** [comment]
Tab recording is specific to your current tab. If you want to record throughout your browser, you should use desktop mode (you can select to record your browser only).

**Comment by GonzaloSP** [comment]
That's right. I tried Desktop mode but still only records the current tab. I granted the right privacy permissions yet no luck. Any suggestion?

**Comment by git-hub-tig** [comment]
some problem

**Comment by Ethan-looplus** [comment]
The same trouble in Win 10 (AMD Ryzen 7 4700U with Radeon Graphic).

**Comment by mistermau** [comment]
Yup. Floating head camera seems to be locked in on only the tab it started on. This extension would be perfect if the camera view floated on top of everything instead of being tied to a tab.

**Comment by alyssaxuu** [comment]
Should be working in the new MV3 version. The camera also floats on top of all windows now in Screen recording mode through Picture in Picture.
