### ISSUE TITLE
load unpack Developer mode

### ISSUE THREAD

**Issue by 5374r3** [alyssaxuu/screenity#136]
list of error i got: 

1.Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details
2.'content_security_policy': Ignored insecure CSP value "'unsafe-inline'" in directive 'script-src'.
3. Unchecked runtime.lastError: The extensions gallery cannot be scripted.
4. Error handling response: TypeError: Cannot read properties of undefined (reading 'id')
5. Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab).

i try to change **manifest.json** with **manifest version 3** i got error in **background.js**

**Comment by alyssaxuu** [comment]
Should be fixed now in the new MV3 version :)
