### ISSUE TITLE
transcription, speech to text

### ISSUE THREAD

**Issue by forresto** [alyssaxuu/screenity#14]
Accessible transcriptions / captions is one more column for your [feature matrix](https://docs.google.com/spreadsheets/d/1juc1zWC2QBxYqlhpDZZUNHl3P6Tens6YiChchFcEJVw/edit#gid=0). I don't think that any screen recording tools have this! It would be nice to be able to share a screen recording with sync'ed transcript, and add headings to have an outline to skip around the recording, reply inline... Accessible UX to help everybody = inclusive design.

https://voice.mozilla.org/stt might be a starting place. 

I'd love to contribute, is anybody else interested?

**Comment by alyssaxuu** [comment]
That's a cool idea, it would definitely be helpful. I'm personally not very sure how to implement this, but I can have a look.

**Comment by alyssaxuu** [comment]
I've been looking into it, and I decided to scrap it for the Screenity extension, but if there's a desktop version (I will get to starting on that soon & evaluating whether it's something that would be worth it) it's something I will consider. Closing since it's out of scope for the extension.
