### ISSUE TITLE
The recorded MP4 files cannot be opened locally

### ISSUE THREAD

**Issue by longweiqiang** [alyssaxuu/screenity#142]
![image](https://user-images.githubusercontent.com/22344864/165488643-e0631bb0-2dcc-4a5d-b616-dbce27a62b3c.png)

**Comment by zkjDream** [comment]
Same problem

**Comment by thejohnha** [comment]
Opens in VLC, but not in QuickTime Player.

**Comment by alyssaxuu** [comment]
Should be fixed in the new MV3 version.
