### ISSUE TITLE
can't record computer audio?

### ISSUE THREAD

**Issue by edjusted** [alyssaxuu/screenity#144]
I can't seem to get screenity to record computer audio.

e.g. if I have music running in the background, or I'm showing a Youtube clip as part of my recording

I've tried testing with different sound-producing-apps in the background, and/or Chrome tabs, and different recording settings (record window, record tab, record desktop).

The recording picks up my microphone with no problem, but any audio produced by the computer itself doesn't get recorded.

Is this expected behavior or is there a setting or something that I'm missing?

**Comment by alyssaxuu** [comment]
If you're on Mac and using the desktop capture option, you will not be able to record your computer audio. I believe in Windows it should work, let me know if that is the case.

**Comment by edjusted** [comment]
Ah, ok. Yes, I'm on a Mac so that's too bad.

**Comment by StuartHemming** [comment]
I'm running on Win10 and I can get it to record audio regardless of the input device I select

**Comment by thejohnha** [comment]
@alyssaxuu just wondering if you're aware of this extension (usebubbles.com): https://chrome.google.com/webstore/detail/bubbles-async-video-colla/ppbfhhgcdehhbjigifndnfmcihegokbb

I tested it and it allows audio recording in any scenario on macOS (tab, window, desktop).

**Comment by alyssaxuu** [comment]
> @alyssaxuu just wondering if you're aware of this extension (usebubbles.com): https://chrome.google.com/webstore/detail/bubbles-async-video-colla/ppbfhhgcdehhbjigifndnfmcihegokbb
> 
> I tested it and it allows audio recording in any scenario on macOS (tab, window, desktop).
> 
> It doesn't have the sweet annotation and other features of Screenity, but it does allow you to record audio on Mac... Thanks for your awesome work.

Based on testing, Bubbles cannot record system audio in macOS when recording the entire screen, unless it is picked up by the microphone, which is the same behavior of Screenity (although I rebuilt it from zero since then, so things might have changed from how the older version worked).
