### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by sr2echa** [alyssaxuu/screenity#147]
Hi,
your repo here,
Has been stolen & re-uploaded by the GitHub user: https://github.com/allaboutishaan/
Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/allaboutishaan/Screensy
Sorry to bring you this bad news

**Comment by Iey4iej3** [comment]
@alyssaxuu You have your copyright on your MIT license. They use your codes without preservation of the copyright or the license is illegal (even if they use a different logo, teaser image, description and design, let alone the same). You could act professionally. You could reclaim at https://support.google.com/legal/troubleshooter/1114905?rd=2#ts=1115658%2C1115673
