### ISSUE TITLE
Issue in code, recording seems to fail

### ISSUE THREAD

**Issue by norm-git** [alyssaxuu/screenity#149]
![image](https://user-images.githubusercontent.com/63025079/178116004-d4dcc9e6-cc97-42a2-9441-96c001753045.png)

**Comment by jsaponara** [comment]
I've seen this on brave but not on chrome.  What browser [and ideally version] were you using, on what platform?

**Comment by alyssaxuu** [comment]
Yep, getting to this ASAP.

**Comment by alyssaxuu** [comment]
Fixed in the new MV3 version.
