### ISSUE TITLE
forwaring and rewind video not working? 

### ISSUE THREAD

**Issue by codeagencybe** [alyssaxuu/screenity#15]
Hello

I just tried your extension and it works magnificent. 
But I noticed some problems with the playback of mp4 and webm after saving it to disk. 
For some reason I can not rewind, fast forward or use the default "skip" buttons from windows media player like +10 or +30 seconds. Also I can't drag the handle to a specific location where I want the playback to start. 

I haven't modified the video in anyway. 
Just simple recording and then save as MP4 and WEBM as I wasn't sure if it was something with the file format specific, but it happens to both of them. 

Not the biggest problem I would say, but I can imagine it's frustrating if you need to quickly rewatch a small piece/few seconds from a video that is 10 minutes long. 
Nope, can't do that. It jumps back all the way to start and you have to force watch the entire part again. 

I tried on different devices as well. Shared on my mobile phone, ipad, etc... same problem everywhere. 
Seems like there is something disabled/permissions that does not allow to use regular media controls.

**Comment by alyssaxuu** [comment]
It's a [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=642012) that causes the recordings made with MediaRecorder to have no duration specified (set to Infinity), causing issues with seeking. It could be fixed through FFMPEG, but as I mentioned in #7 and #1, using a back-end to process the videos would be very costly unfortunately so it's not something I can do ATM.

**Comment by charitarthchugh** [comment]
Interestingly, I can scrub through just fine using Gnome Videos (Totem), which is based on GStreamer.

**Comment by alyssaxuu** [comment]
Fixed in the latest version.

**Comment by christhomas211** [comment]
> Hello
> 
> I just tried your extension and it works magnificent. But I noticed some problems with the playback of mp4 and webm after saving it to disk. For some reason I can not rewind, fast forward or use the default "skip" buttons from windows media player like +10 or +30 seconds. Also I can't drag the handle to a specific location where I want the playback to start.
> 
> I haven't modified the video in anyway. Just simple recording and then save as MP4 and WEBM as I wasn't sure if it was something with the file format specific, but it happens to both of them.
> 
> Not the biggest problem I would say, but I can imagine it's frustrating if you need to quickly rewatch a small piece/few seconds from a video that is 10 minutes long. Nope, can't do that. It jumps back all the way to start and you have to force watch the entire part again[.](https://quotesgenerator.co/)
> 
> I tried on different devices as well. Shared on my mobile phone, ipad, etc... same problem everywhere. Seems like there is something disabled/permissions that does not allow to use regular media controls.

Try some latest version of video player and [reading quotes](https://quotesgenerator.co/) it will help your problem
