### ISSUE TITLE
#REQUEST QUALITY RECORD

### ISSUE THREAD

**Issue by norm-git** [alyssaxuu/screenity#150]
Hi, 
Please, if can add for record in 1080

**Comment by Education-AIT** [comment]
Bump this

**Comment by Pau111111** [comment]
It would be the best screen recorder if it could record in 1080

**Comment by alyssaxuu** [comment]
I believe it should record in 1080p in the current version if your system can handle it. But I could add an option to force the quality (even though as it works locally it will take a lot of memory and generate a huge file).

**Comment by alyssaxuu** [comment]
Added an option under the "..." menu in the popup to select between different resolutions in the [latest Screenity release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.4). It will still depend on the device specifications, if it's not powerful enough it will only support up to 480/720p.
