### ISSUE TITLE
Chrome Manifest V3 support

### ISSUE THREAD

**Issue by enmohsinali** [alyssaxuu/screenity#152]
First of all I appreciate your effort to build Screenity tool which I think is better than all the other tools in chrome marketplace right now.
Can you please let me know are you working on to upgrade the Manifest V3 ? or do you have plan. ?
I hope you know about V2 support has been end.

**Comment by luis-nach** [comment]
Hello,
we have completed the migration to V3... it is not an easy job...
If you are interested in getting the V3 please contact me here.
luisnach@proton.me

**Comment by enmohsinali** [comment]
Please do not trust this @luis-nach person.
He is a scammer.
Asking me to pay for an open source project without giving any evidence about V3 version.
@alyssaxuu please remove his comment and report this account.

 
![image](https://user-images.githubusercontent.com/37579751/181234568-128baf94-6d4e-43ae-91b2-215ce0e17a66.png)

**Comment by luis-nach** [comment]
Do you feel like a better person?
Do you wait for the work of others instead?
You could contribute rather than complain, or wait like a coward for Alyssa to do the work for you.

**Comment by enmohsinali** [comment]
You have Joined github just 6 days ago and pretending to know this platform better.? Huh..
You are not even the contributor.
When I ask to provide complied version you refused so how could someone trust you. ?

**Comment by luis-nach** [comment]
I'll tell you the truth, I still lost the desire to send it to you.
I will only send it to real contributors and then they will decide what to do with it.

**Comment by enmohsinali** [comment]
I don't need it from you. And yes please send it to the contributors or whoever you want to send. You have nothing to send.
The truth is that you don't have any V3 code and when someone will send you the eth in your wallet you will delete your profile.
No one will trust a new profile with no contribution no social prof and no background.
This child has revealed your scamming.

**Comment by alyssaxuu** [comment]
Sketchy stuff. Anyway I will be hoping to port Screenity to MV3 in the coming months, I'm thinking about first releasing the MV3 version, and then hopefully by end of year / start of 2023 have a brand new version of Screenity. Just a bit busy right now with my motion graphics editor.

**Comment by enmohsinali** [comment]
Thank you so much @alyssaxuu .
I appreciate your effort. Good luck with TBD.

**Comment by Cooper4111** [comment]
@enmohsinali I'm working now on somehow similar project and the problem is much deeper than just MV3. It's about `SharedArrayBuffer` being broken in ffmpeg wasm core. Check [this](https://github.com/ffmpegwasm/ffmpeg.wasm/issues/263) issue. So first of all it's up to ffmpeg support team.

**Comment by enmohsinali** [comment]
@Cooper4111 
I see.
Would you like to share the repo ?

**Comment by Cooper4111** [comment]
@enmohsinali I'd be happy to, yet it is proprietary. :)
I think after release we might publish a topic about all the MV3 pitfalls we met during development. Somewhere on Habr e.g..
