### ISSUE TITLE
Doesn't support camera outside browser and other Tabs

### ISSUE THREAD

**Issue by skedaddl3** [alyssaxuu/screenity#155]
I noticed the camera only works for one specific tab where the screenity extension started; the Record button also hangs and takes too much time loading, but it's still clickable.

A temporary workaround I found to fix the Disabled Camera and Microphone was to search for something in Google or just visit the Google site.

**Comment by alyssaxuu** [comment]
Should be working now in the new MV3 version of Screenity. For outside the browser, I've used Picture in Picture mode to allow for the camera to float on top of any application.
