### ISSUE TITLE
Browsers "pixilation" issue

### ISSUE THREAD

**Issue by abddu1** [alyssaxuu/screenity#16]
Hi,

Please fix the title if the word is wrongly used.

I'm seeing the following in chrome Version 89.0.4333.0 (Official Build) canary (64-bit)
It appears at the top of the page during recording, and is recorded as well.

![image](https://user-images.githubusercontent.com/23237675/99958793-09a63380-2d9b-11eb-9d29-e2ea31b4c5a6.png)

Any way to fix it?

**Comment by alyssaxuu** [comment]
This is very odd - can you share a link to the page you're trying to record? Theoretically there should be no conflicts with the CSS...

**Comment by abddu1** [comment]
The issues appeared in all website, regardless of CSS and animation used.

I initially used it on the following websites (both highly animated):
https://witnessestohistory.museeholocauste.ca/about/
http://winehistory.ge/en/

Just tested with Chrome Version 87.0.4280.66 (Official Build) (64-bit) 

it worked well.

This seems an issue in Chrome Canary

**Comment by alyssaxuu** [comment]
Oh dang, you are right. I'm not sure what it is but in Chrome Canary the color picker just seems to break which is what causes the issue. Maybe some sort of CSS property that is injected or something, really strange though. I'll look into it.

**Comment by abddu1** [comment]
Great product!

Thanks a lot, 

Closing this for now
