### ISSUE TITLE
Suggest - Feature at download

### ISSUE THREAD

**Issue by Bkz507** [alyssaxuu/screenity#160]
Hi, 

Thanks so much for so usefull tool. I really love Screenity. 

I only have a doubt or suggest: 

When I download the file after finishing the record i cannot move forward o back on the record bar. 

Is this an issue? or there is a way I can use the reproduction bar to go to a specific moment of the record?

Thanks so much for the help.

**Comment by alyssaxuu** [comment]
I've fixed this in the MV3 version of Screenity.
