### ISSUE TITLE
Remove part of the video

### ISSUE THREAD

**Issue by leadra** [alyssaxuu/screenity#161]
Remove part of the video
after apply ,video all block
use mp4 download,for shotcut...canot import,for potplayer audio video are not current(MPC-HC is OK)
1.如果使用剪輯，影片會直接變成全黑
2.如果直接轉成mp4下載後，則是影片播放有點問題，尤其套用到剪輯軟體內會失敗

正在更新 Chrome (6%)
版本 104.0.5112.102 (正式版本) (64 位元)

**Comment by ppYoung** [comment]
亲，你的邮件东阳已经收到了

**Comment by alyssaxuu** [comment]
Should work in the new MV3 version of Screenity.
