### ISSUE TITLE
Not working properly in Incognito mode

### ISSUE THREAD

**Issue by Iey4iej3** [alyssaxuu/screenity#164]
When capturing a video for a tab for a descent amount of time (say, more than 1 minutes), one cannot pause or stop capturing, and no file can be obtained.

**Comment by alyssaxuu** [comment]
I've overhauled the extension in the newest MV3 version, is this still happening?

**Comment by PoLaKoSz** [comment]
Sadly yes.

Version: Sreenity 3.1.12
Browser: Brave
![image](https://github.com/user-attachments/assets/dff44db3-8816-434b-84e2-c33e5cd8636b)
