### ISSUE TITLE
"Can't record in this page" bug

### ISSUE THREAD

**Issue by AE720** [alyssaxuu/screenity#169]
I know there are some pages that recording will not work such as the new tab page and that part is fine as the button is grayed out. However If I click from "Tab Only" to "Desktop", or vice versa, that same button that says "Can't record in this page" becomes clickable:
![image](https://user-images.githubusercontent.com/63013864/200404509-de9734c2-512d-4b9d-80d8-7441e3963567.png)

It then says "Starting recording..." and then I get the prompt to select a Window/Tab but then nothing happens and naturally the console floods with ERR_UNSAFE_REDIRECT.

**Comment by alyssaxuu** [comment]
Should be fixed in the MV3 version of Screenity :)
