### ISSUE TITLE
Slider knob is not centered on it's track

### ISSUE THREAD

**Issue by vknt** [alyssaxuu/screenity#17]
Congrats on this release @alyssaxuu! This could become an extension that I use daily..
This is a small visual improvement, I just got started testing it :)

![Slider-Alignment](https://user-images.githubusercontent.com/239392/100022840-b8954000-2d98-11eb-9f13-9f42a9b75e01.png)

**Comment by alyssaxuu** [comment]
Fixed it in the 2.2.2 release.
