### ISSUE TITLE
Seeker Slider Not Working

### ISSUE THREAD

**Issue by ya332** [alyssaxuu/screenity#171]
Hello,
I am in Windows 10 running this extension in Google chrome latest version.
I am not able to slide the seeker in the video. 
Thanks

**Comment by Ik00k0** [comment]
Same here. Videos created in all formats cannot be seeked either.

Btw Thank you so much for this software Alyssa. It's incredible.

**Comment by Ik00k0** [comment]
I've found that downloading the video and using handbrake to quickly convert it makes it possible to seek within the video slider. @alyssaxuu may be busy so it's a meaningful work around in the meantime

**Comment by alyssaxuu** [comment]
I've fixed this in the newest MV3 version of Screenity :)
