### ISSUE TITLE
[Feature request] Add basic shapes

### ISSUE THREAD

**Issue by skys215** [alyssaxuu/screenity#172]
Hi,
 thanks for the nice tool.

Though pen tool is the most basic tool, hope to add rectangle and circle tool as well for making prettier shapes while recording.

Thanks.

**Comment by alyssaxuu** [comment]
I want to do a MV3 version from the ground up so I'm not really adding to the current version unfortunately. I might add this specific feature to the newer one.

**Comment by 340rahul** [comment]
Is it an open source project and are you open to accepting contributions on it? I'd love to contribute to the MV3 version.

**Comment by alyssaxuu** [comment]
Added shapes with fill and stroke in the newest MV3 version :)
