### ISSUE TITLE
CRX_FILE_NOT_READABLE when trying to install extension

### ISSUE THREAD

**Issue by andersfloor** [alyssaxuu/screenity#173]
When I try to install the extension, I get the message CRX_FILE_NOT_READABLE 
![image](https://user-images.githubusercontent.com/16984414/204101499-b3b20492-2644-40ce-9b53-b8e7160f0ea5.png)

I'm installing it from this link
https://chrome.google.com/webstore/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji

Chrome version 107.0.5304.122 (Official Build) (64-bit), Windows 10 Pro

**Comment by alyssaxuu** [comment]
Let me know if you still have any other issues with the newest MV3 version. If not, I will close the issue.
