### ISSUE TITLE
can it be used to record zoom meeting (web form)?

### ISSUE THREAD

**Issue by lweo** [alyssaxuu/screenity#175]
I tried it, but I failed to stop  recording and save the video after the long time of recording.  

click the pause button, it doesn't give any response. click the Screenity menu , it doesn't show the stop recording, instead show "loading".

I tried it on chrome incognito webpage, it will "download" the meeting in real time, but the audio gets bizarre and the CPU is consumed a lot.

chrome: Version 100.0.4896.127 (Official Build) (64-bit)
extension:  2.8.6
test website:  https://us06web.zoom.us/wc/join/[meeting code]

appreciated your work a lot!

Thank you in advance!

**Comment by alyssaxuu** [comment]
Should be working now in the MV3 version of Screenity.
