### ISSUE TITLE
what's the saving method when I forbid the site's cookies? is filesaver more stable than streamsaver?

### ISSUE THREAD

**Issue by lweo** [alyssaxuu/screenity#177]
when I forbid the particular site's cookies and start to record, it pop up the downloading dialogue. But when allow the cookies, it will work on the background, however, I usually can't save the video after stop recording! when I stop it, the new window doesn't show the recording video. when I tap "download", it prompts "downloaded failed, network error"

I'm guessing the extension is using filesaver.js when it can't save the file on the disk. And it's using streamsaver.js instead  when it can save files on the disk. Am I right?

**Comment by alyssaxuu** [comment]
Should be fixed now in the MV3 version of Screenity.
