### ISSUE TITLE
Conflict with Free Download Manager

### ISSUE THREAD

**Issue by etherealxx** [alyssaxuu/screenity#178]
Everytime i hit the recording button, FDM mistakenly thought it was a download, and try to download screenity.htm. The popup sometimes annoys me when i want to record something.

![2022-12-21 09_18_23-Free Download Manager](https://user-images.githubusercontent.com/64251396/208805309-6fb20fc0-35b6-4657-91e0-935055c8957f.jpg)

FDM: https://www.freedownloadmanager.org/

**Comment by alyssaxuu** [comment]
Should be fixed now in the new MV3 version.
