### ISSUE TITLE
Add option to upload on Youtube

### ISSUE THREAD

**Issue by Its-Alex** [alyssaxuu/screenity#18]
Awesome extension! This would be awesome to be able to upload on Youtube too!

**Comment by megaroeny** [comment]
I think that's going way beyond what this tool is meant to do. YouTube has a huge API and way too many features, forms, etc. Personally, I would rather upload on YouTube than using this tool.

**Comment by alyssaxuu** [comment]
I guess it'd be possible to add different sharing options, why not. I could look into it, it's just tricky since it's not just one click and you're done, you also need to give it a title, privacy permissions, etc. so that would require a modal of some sort.

**Comment by Its-Alex** [comment]
> I think that's going way beyond what this tool is meant to do. YouTube has a huge API and way too many features, forms, etc. Personally, I would rather upload on YouTube than using this tool.

In my case, I use loom to publish demo movies to other developers, so the option to share a movie with only one link is really useful. I was proposing Youtube since I think this can be a good replacement to shared content without taking a lot of space in Drive.

**Comment by megaroeny** [comment]
> > I think that's going way beyond what this tool is meant to do. YouTube has a huge API and way too many features, forms, etc. Personally, I would rather upload on YouTube than using this tool.
> 
> In my case, I use loom to publish demo movies for other developers, so the option to share a movie with only one link is really useful. I was proposing Youtube since I think this can be a good replacement to shared content without taking a lot of space in Drive.

Ah okay, yeah good point! As Alyssa said, the form would have to be minimal, then I could see it being useful.

**Comment by meshoo12** [comment]
That will be very useful specially when sharing links with people who don't trust unknown domains.

**Comment by alyssaxuu** [comment]
I've been looking into adding Youtube as an option for the MV3 version of Screenity, however when I've looked at the Youtube API rate limits, it doesn't seem feasible to support this feature, especially considering the user base. They seem to have made it progressively more limited over the years, to the point where only a few uploads a day would be possible in total. 

There is the option to request the limit to be increased, but as far as I understand, this would mean paying for the extra requests. So unless there is some change, I don't think I'll be adding Youtube support anytime soon.

I'm also developing the cloud version of Screenity too which allows link sharing by saving the videos automatically to the cloud, which will solve the issue of easily sharing videos with others anyway.

**Comment by Its-Alex** [comment]
Hello :wave: , I find it unfortunate because, from my perspective, Screenity's advantage lies precisely in being free and open source. Moving towards a cloud solution may just result in it becoming a competitor to business-oriented tools like Loom.

Additionally, it seems to me that Screenity could leverage the user's Google account who is using the extension, allowing them to unlock the limit by making a payment themselves.

In any case, thank you for the time taken to address this issue.

**Comment by alyssaxuu** [comment]
> Hello 👋 , I find it unfortunate because, from my perspective, Screenity's advantage lies precisely in being free and open source. Moving towards a cloud solution may just result in it becoming a competitor to business-oriented tools like Loom.
> 
> Additionally, it seems to me that Screenity could leverage the user's Google account who is using the extension, allowing them to unlock the limit by making a payment themselves.
> 
> In any case, thank you for the time taken to address this issue.

For clarity, the idea is to support both: a forever free + open source version of Screenity, and a paid one for users who want to leverage the cloud to share videos with others, do more intensive editing, and more. I don't think it's incompatible, and IMO it's a bit unreasonable to expect no monetization given the time spent developing, handling support, and much more. I can't really justify working on it otherwise as it would not be sustainable in the long run (which happened last time).

It's true though that I may be able to do the Youtube integration some other way though, either a user-provided API key, or (something I saw another tool do) using a headless browser with the user's Google account to upload to Youtube directly. I might look into it at some point, although I'm prioritizing some other features and improvements at the moment.
