### ISSUE TITLE
not work in chrome2023 version

### ISSUE THREAD

**Issue by QiaoHaiZhong** [alyssaxuu/screenity#180]
Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details.
'content_security_policy': Ignored insecure CSP value "'unsafe-inline'" in directive 'script-src'.
Error handling response: TypeError: Cannot read properties of undefined (reading 'id')
Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab).

**Comment by faizankhalil007** [comment]
did you find a solution?

**Comment by alyssaxuu** [comment]
I've updated the extension to MV3 now :)
