### ISSUE TITLE
Can't edit files / merge to one

### ISSUE THREAD

**Issue by vellkan** [alyssaxuu/screenity#181]
I've made some videos to create a movie for Youtube, but unfortunatelly I can't edit it in Premier Pro or any other video editor.
It's not important if I save them as WebM oraz MP4, it's not working at all.

I've lost almost 5 hours today to record videos and now I need to find better solution.

**Comment by alyssaxuu** [comment]
I've fixed the video encoding in the newest MV3 version of Screenity.
