### ISSUE TITLE
I recommend using the WebM with H.264, for example, mimeType: "video/webm;codecs=h264".

### ISSUE THREAD

**Issue by avan06** [alyssaxuu/screenity#185]
Hi,

Thank you for providing such a great tool.

I would suggest changing the parameter 【mimeType: "video/webm;codecs=vp8,opus" or mimeType: "video/webm"】 to 【mimeType: "video/webm;codecs=h264"】.

The advantage of this change is that it allows for quick conversion of the webm format to mp4 format, for example using the command "ffmpeg -i input.webm -c copy output.mp4".

If you want to use it in a safer manner, you can also use the method 【isTypeSupported】 to check if it is supported.
For example:
MediaRecorder.isTypeSupported("video/webm;codecs=h264") ? "video/webm;codecs=h264" : "video/webm;codecs=vp8,opus"
___

# Converting WebM with H.264 video to MP4

In some rare cases the .webm file will contain H.264 video and Vorbis or Opus audio(for example .webm files created using the [MediaRecorder API on Chrome 52+](https://addpipe.com/media-recorder-api-demo/?ref=deconstruct) ). In such cases you don’t have to re-encode the video data since it’s already in the desired H.264 format (re-encoding is also not recommended since you’ll be loosing some quality in the process while consuming CPU cycles) so we’re just going to copy over the data
![image](https://github.com/alyssaxuu/screenity/assets/6281616/b6a0d0bc-b126-4294-9f69-2714b47b65e6)
https://blog.addpipe.com/converting-webm-to-mp4-with-ffmpeg/

**Comment by ppYoung** [comment]
亲，你的邮件东阳已经收到了

**Comment by alyssaxuu** [comment]
I have released a new version of Screenity that uses FFmpeg WASM under the hood to encode videos properly in MP4, should also be good for the WEBM videos.
