### ISSUE TITLE
make camera dot configurable where to start  

### ISSUE THREAD

**Issue by lenili** [alyssaxuu/screenity#189]
## What is the problem 
I want to make a lot of screen videos with my picture in there. 
The camera dot always starts in the left upper corner (where in my case the navigation sits).
So I always have to move the dot to left downwards as soon as screencapture starts. 

## Proposed solution 
1. If I could already choose in the settings for instance that I want it to start the camera dot: 
- Left upper corner 
- left down corner 
- right upper corner 
- right down corner 

2. even better the camera dot stays always there where left the last capture 

Thank you :) 
Ps: it is great and very helpful

**Comment by alyssaxuu** [comment]
Just released the MV3 version of Screenity which should save the position of camera, toolbar, and UI in general.
