### ISSUE TITLE
Audio still being recorded despite disabled before start recording

### ISSUE THREAD

**Issue by hezral** [alyssaxuu/screenity#19]
Hello, first off thank you for making this. 

I tried it on Version 86.0.4240.183 (Official Build) (64-bit) on elementary OS 5.1.7

Behaviour:
Both Tab Only and Desktop recordings, disabled webcam and mic recording still produces a recording that recorded audio from the mic. 

I've uploaded a sample of this showing the behaviour
https://drive.google.com/file/d/1QBboe3LqJZnmfz5IG4kOufgbey4DhvOQ/view?usp=sharing

**Comment by alyssaxuu** [comment]
This is very strange, I tried tab and desktop recording with the audio disabled from the popup and it did not play. Not sure what the issue is - maybe reinstall the extension or try updating Chrome?

**Comment by hezral** [comment]
i've just removed and reinstall it and now its working as expected. strange indeed, i'll close this for now and monitor
