### ISSUE TITLE
Camera Only not saving

### ISSUE THREAD

**Issue by TylerFrom814** [alyssaxuu/screenity#193]
Noticed a bug on several systems where using the "Camera Only" function to record a video, then when you click the checkmark to save it, nothing happens...the video just disappears.  The Tab only and Screen options work fine, it takes you to the save/download page after recording, but the camera only record does nothing after you record and click the checkbox.

**Comment by alyssaxuu** [comment]
Should be fixed in the Manifest V3 of Screenity.
