### ISSUE TITLE
Extension not working locally 

### ISSUE THREAD

**Issue by SaadAI2** [alyssaxuu/screenity#194]
When attempting to load the extension locally by selecting "Load unpacked," I encounter a "manifest_version 2" error, indicating that manifest version 2 is no longer supported.

**Comment by alyssaxuu** [comment]
Manifest version 3 coming soon :) Should still work with version 2 though, despite the error.

**Comment by alyssaxuu** [comment]
Fixed with the newest Manifest V3 version of Screenity :)
