### ISSUE TITLE
MP4s not compatible on macOS 14.0

### ISSUE THREAD

**Issue by fuzenco** [alyssaxuu/screenity#196]
On macOS 14.0 when exporting to MP4, the OS isn't able to open the file. Error is: “The file isn't compatible with QuickTime.” I’ve tested it multiple times with the same error result.

**Device:**
macOS 14.0
Apple M2 MacBook Pro

**Comment by thejohnha** [comment]
See: https://github.com/alyssaxuu/screenity/issues/7
You can open the file with VLC.

**Comment by alyssaxuu** [comment]
Fixed in the latest MV3 version.

**Comment by fuzenco** [comment]
> Fixed in the latest MV3 version.

Honestly, this update is wow! Incredible work @alyssaxuu . Saving to MP4 works perfect and the UI updates are wonderful. Amazing work. You are a genius.
