### ISSUE TITLE
More levels of blur effect

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#197]
Hi @alyssaxuu, i tried a blur effect and it is too weak for me, so almost the whole room is still pretty clearly visible. I don't know, where I have seen that, but someone has more levels (I think 2 of them) of blur - something like yours and more aggressive one. Could you at least think about this "use-case" (wide camera in home environment, but I don't want to show my whole room :D), please? It would be great to have an option for handle with it. I know there are fully colored variants of background, but they use pretty aggressive colors, so it's a little to much aggressive for me. Blur looks pretty decent, but it's just too weak as I noted (I hope you understand and my bag of words isn't just something good to be thrown to trash can :( ).

**Comment by alyssaxuu** [comment]
I could look into adding a stronger blur, I could maybe switch the intensity of the existing one. I'm planning on adding more options overall for the effects anyway, including custom options. Thanks for the feedback :)

**Comment by alyssaxuu** [comment]
I've added a stronger blur for now as default. Might make it custom or add more options in the future. It will be version 3.0.1 on the Chrome Store, but I've made a release on GitHub already.

**Comment by ceskyDJ** [comment]
Thanks! I tried the new version and it looks good. There's a problem with blinking part of a video — it can't correctly detect table behind me. I don't know, how much you can do with this, so I let it go for some time and then maybe prepare a issue with better description and demonstration.
