### ISSUE TITLE
Settings for keyboard shortcuts

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#199]
Hi! Is there a way how to change or (my personal preferred option) turn off some keyboard shortcuts? Thank you for your possible help with this!

**Comment by alyssaxuu** [comment]
I made an article about setting and viewing the keyboard shortcuts here: https://help.screenity.io/getting-started/77KizPC8MHVGfpKpqdux9D/how-to-use-and-set-keyboard-shortcuts/4nvwhwXv3w5w9H9ZecUgFE

**Comment by ceskyDJ** [comment]
It is just what I'm looking for. Thanks a lot!
