### ISSUE TITLE
cant find a recorded video on windows

### ISSUE THREAD

**Issue by maheshmnj** [alyssaxuu/screenity#2]
Thanks for this great and simple to use software and it looks promising,I tried it out on windows but once the recording was stopped I couldn't see the recording being saved anywhere on the system.I would request a feature where in user can customize the location where the recording is stored also there should be a standard location where it is stored and should also be mentioned somewhere inside the application so that user is aware about it.

**Comment by alyssaxuu** [comment]
Did you get to the video editing screen or the controls just disappeared? You have to click on the checkmark after pausing in order to save the video, then click on the Download button which will automatically download the recording in the downloads folder (and will show up in Chrome also in the bottom bar).

**Comment by megaroeny** [comment]
I can confirm it works just fine for Windows 10, and I got to the video editing screen. 🙂

**Comment by maheshmnj** [comment]
> Did you get to the video editing screen or the controls just disappeared? You have to click on the checkmark after pausing in order to save the video, then click on the Download button which will automatically download the recording in the downloads folder (and will show up in Chrome also in the bottom bar).

@alyssaxuu  Sorry It does work pretty well now, not sure why I didn't get the download window on my first try yes it does work fine @megaroeny  thanks for the confirmation

**Comment by maheshmnj** [comment]
Also not sure if that's intentional the wording should be **stop recording** instead of **stop sharing** please correct me if you have some other thoughts on it.

**Comment by megaroeny** [comment]
> Also not sure if that's intentional the wording should be **stop recording** instead of **stop sharing** please correct me if you have some other thoughts on it.

I'm guessing you're referring to the floating bar at the bottom center of your screen. That is shown by the Chromium browser itself, not Screenity.

There is a Pause button in the toolbar, that lets you Save and Pause or Discard.
![image](https://user-images.githubusercontent.com/1559447/99968601-5243f980-2d67-11eb-9e59-4bfda13edce6.png)

Click play and it becomes:
![image](https://user-images.githubusercontent.com/1559447/99968630-5cfe8e80-2d67-11eb-8be3-ca7f68b157f7.png)

**Comment by alyssaxuu** [comment]
> Also not sure if that's intentional the wording should be **stop recording** instead of **stop sharing** please correct me if you have some other thoughts on it.

Oh, that's the UI that gets added by Chrome when you make a desktop recording, I have no control over how it looks and what the wording is unfortunately.

**Comment by maheshmnj** [comment]
Oh thanks for clarification I don't really have much idea on the web
