### ISSUE TITLE
Option to have screen and cam simultaneously like in zoom-screensharing?

### ISSUE THREAD

**Issue by casinojeffrey** [alyssaxuu/screenity#204]
Hi there. i am checking your product at the moment and was wondering if you also offer the option to have screen and cam simultaneously like in zoom-screensharing where a circled face is somewhere in the corner of the screen as well as the screenrecording.

hope the question makes sense somehow. for better reference i also added a sketch
![Unbenannt-2023-12-21-2257](https://github.com/alyssaxuu/screenity/assets/46980342/ad4c08d2-5ec7-402e-9f0f-24e61bee610d)

**Comment by alyssaxuu** [comment]
That's the main use case of the product, you can put the camera anywhere on the page while recording, or if you're recording the whole monitor, you have the option of using Picture in Picture mode (which should launch automatically, or you can click on the PiP button when hovering on the camera to toggle it) to keep the camera visible on top of all your apps. Hope that helps :)

**Comment by alyssaxuu** [comment]
Closing as question has been answered.
