### ISSUE TITLE
Weird additions to the webpage example.com

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#206]
Hi @alyssaxuu! I found another issue while recording example.com. Screenity adds some rectangles to the page, so the content of the webpage is full of them. I think this video explains it better than hundreds of words:

https://github.com/alyssaxuu/screenity/assets/48548230/6909e8e3-e006-44c9-9020-11cf6115e85d

**SW details:**
- **Browser:** Google Chrome 120.0.6099.129 (Official Build) (64-bit)
- **Screenity version:** 3.1.0

**Comment by ceskyDJ** [comment]
You're just right. It has styling of `div`s. I think it will be better to override these styles, because this problem could appear on more pages that ignores the fact it isn't the best way, how to select elements in CSS.

Thanks for looking into it!

**Comment by alyssaxuu** [comment]
Fixed in the [3.1.2 release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.2), will be live in the Chrome Store soon.
