### ISSUE TITLE
Camera doesn't work on secondary screen

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#207]
Hi @alyssaxuu! I have a pretty simple monitor setup (notebook screen as secondary and external monitor as primary):
![image](https://github.com/alyssaxuu/screenity/assets/48548230/f6cbfb1e-e18d-4dea-bc08-bca8e6eb3702)

When I run Screenity on the primary display (the bigger external monitor), it works well – camera shows up normally and usually contains a person in front of it (when the camera isn't covered).

On the secondary display (notebook's monitor) camera doesn't appear at all. Interesting is that when I drag the window to the secondary screen, the camera just disappears and appears again after moving the window back. It cause one more (but just a little) problem – it breaks positioning of camera and recording toolbar.

You can see everything in this video (yeah, it's very wide, but I didn't come up with a better way, how to record it):

https://github.com/alyssaxuu/screenity/assets/48548230/abacb136-f370-48c8-a54f-0402c192c440

**Comment by alyssaxuu** [comment]
Ah hmm I see, I will need to see if I can handle this case with some event when switching the window's context / moving the window around, or some other way... I think even in this case though you can easily fix this by either switching the camera on off again, or resizing the browser window (as it detects if it's offscreen automatically). Still good to try and prevent this from happening regardless.

**Comment by ceskyDJ** [comment]
Turning off and on again doesn't solve the problem. Even clicking on Screenity icon in Chrome top bar for closing it and again for reopening it doesn't change anything (it's in the video, too, btw). Resizing of the browser window doesn't help, too.

**Comment by ceskyDJ** [comment]
I forgot to add additional context. I tried Screenity on my other setup located at my parents' house. There are opposite situation - the same notebook screen as primary display and a bigger external screen as secondary display. It doesn't work there, too. I can't remember precisely, how it behaves on the primary (notebook) screen, but on the secondary screen, the camera showed up after some playing with it (changing size of the windows, turning Screenity on and off, etc.) as a rectangle (I can't imagine, how it could be display like that) with limited functionality – but it at least worked somehow. I can't provide more details, since I don't have a recording of the behavior and have a Swiss cheese memory :(.

**Comment by alyssaxuu** [comment]
Found the issue, will update on the next release!

**Comment by ceskyDJ** [comment]
So, good job!

**Comment by alyssaxuu** [comment]
Fixed in the [3.1.2 release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.2), will be live in the Chrome Store soon.
