### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by 9E307** [alyssaxuu/screenity#21]
can you add Chinese Language support？Thanks

**Comment by alyssaxuu** [comment]
I am currently working on rolling out new languages as we speak. Catalan and Spanish translations are coming up very soon, and I will be accepting contributions to translate the extension to other languages including Chinese :)

**Comment by alyssaxuu** [comment]
[Here is the file](https://github.com/alyssaxuu/screenity/blob/master/_locales/en/messages.json) to change to adapt to the different languages. The "message" contains the string in the new language to translate to, "description" is just to give you some context where that string will show up in the extension. Aside from that, the detailed description in the Chrome Store ([here](https://chrome.google.com/webstore/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji?authuser=0&hl=en)) has to be translated as well.

The translated JSON file should be in a new folder inside the [_locales folder](https://github.com/alyssaxuu/screenity/tree/master/_locales) and its own folder with its respective language code, [you can look at this table](https://developer.chrome.com/webstore/i18n#localeTable) to see what that code should be.

I have already published the Catalan and Spanish translations, French might be in the works next, but I would really appreciate if people contributed translations of their own languages as well, to make the extension accessible to people all around the world :)

**Comment by alyssaxuu** [comment]
Chinese support is live now :)
