### ISSUE TITLE
ESC key doesn't work properly for blur submenu of toolbar

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#210]
I found similar problem as in #209. When I open blur submenu of the toolbar, it can't be closed by ESC key if I click in the recorded place. I think video will describe it better:

https://github.com/alyssaxuu/screenity/assets/48548230/9264ee48-a31c-4c63-9d9e-448dac74370e

**Comment by ceskyDJ** [comment]
The same problem is for drawing submenu.

**Comment by alyssaxuu** [comment]
Should work fine now, I've tested it while recording and clicking on the page itself and have been able to close with the Esc key.

**Comment by ceskyDJ** [comment]
> I've tested it while recording and clicking on the page itself and have been able to close with the Esc key.

Hmm, so it should work as I think. Where the hell is the problem after?

ESC press doesn't work just after the bubble disappears (I just wait for the disappearing without any other interaction), too. Maybe it'll help you a bit.

**Comment by alyssaxuu** [comment]
Ah I understand now, you mean after the toast disappears - I didn't actually implement it to close with Esc outside the timeframe when the tooltips are visible. I think my reasoning was that a page may use Esc for other purposes, so it might cause some conflict in some cases (the same reason why I avoid using shortcuts besides the ones defined in the manifest file). I've had issues anyway with keys in general as some websites use focus trapping which is hard to override.

I could consider adding them in, I'd just have to see how it feels in context. I could see it potentially being problematic in pages that use popups / modals that can be dismissed with Esc, but I would have to see. I don't think it would be challenging to implement in any case.

**Comment by ceskyDJ** [comment]
I see it as my problem with English communication, so I'm sorry for unclear specification of the issue. I use English passively most of the time (watching some English content, read websites, papers, translating SW to Czech, etc.), but my active knowledge of English is very poor. So, sometimes (like this time, unfortunately) I just don't give clear enough information...

I was thinking about it a little more and I realized that you're just right. Especially for closing modals or special high keyboard-oriented websites in general it could make serious problems. So, it's better to let it without the way for closing it via keyboard.

Maybe there is a even better solution for closing it. But, as you noted, we need some time of using it to figure out, which could it be.
