### ISSUE TITLE
Problem with hover effect of toolbar items on pages like example.com

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#211]
Hi! Hover effect of toolbar items causes troubles on pages like example.com (with bad styling practices). Look at the video, please:

https://github.com/alyssaxuu/screenity/assets/48548230/f44c37d5-7c7d-4be0-83ad-4bae27a03a8d

**Comment by alyssaxuu** [comment]
Fixed, was caused by the styling override.
