### ISSUE TITLE
Blur tool doesn't work

### ISSUE THREAD

**Issue by ceskyDJ** [alyssaxuu/screenity#212]
Hi @alyssaxuu! Blur tool stopped working in 3.1.2. I don't know if I messed it up somehow but it just doesn't work at all. I acts like pencil or select tool which depends on the currently selected tool. You can see, what it's doing in the video:

https://github.com/alyssaxuu/screenity/assets/48548230/eaa05aaf-4d47-45c2-9878-b0d7ea30f1b2

**Comment by alyssaxuu** [comment]
Good catch, I've cancelled the publish of the release in the Chrome Store until I can resolve this as well as the styling issues.

**Comment by alyssaxuu** [comment]
Fixed it, was due to the styling override. Will try to re-publish soon.
