### ISSUE TITLE
Screen recording permissions prompt not working in Vivaldi

### ISSUE THREAD

**Issue by drewbitt** [alyssaxuu/screenity#217]
https://github.com/alyssaxuu/screenity/assets/26885897/d87fab81-0c4c-43fb-adf9-d0e6660ab723

Vivaldi, macOS Sonoma. Extension from Chrome Web Store and tested loading it unpacked too from the latest release - no change. Set area to record in does not change anything. Vivaldi has screen recording permissions in macOS enabled. Other sites like https://www.screencapture.com work fine for the prompt to screen record, so it's possible at least from a site. 

### Extension Permissions

<img width="684" alt="image" src="https://github.com/alyssaxuu/screenity/assets/26885897/2b6cb868-029f-479d-9c61-a7ed2e83c7d5">

### Errors

Nothing in console except `Unchecked runtime.lastError: This function must be called during a user gesture` coming from this extension.

**Comment by drewbitt** [comment]
Resolved by reverting to 3.1.2 which by a quick git blame was before some of the `lastError` additions.

**Comment by alyssaxuu** [comment]
Thanks for flagging, looks like this might be because I moved the permissions code in the service worker to a separate function, and it might need to be inline with the listener to avoid the user gesture issue in some cases. I will release a patch ASAP.

**Comment by alyssaxuu** [comment]
Fixed in the [latest release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.7), just awaiting approval in the Chrome Store to go live, hopefully will be in a day or so.

**Comment by drewbitt** [comment]
Works, thanks!

**Comment by louislefebvre** [comment]
Hello, I do experience the same issue and the exact same error `Unchecked runtime.lastError: This function must be called during a user gesture` when using the browser [Arc](arc.net).

**Comment by KazimirPodolski** [comment]
I'm also getting this `Unchecked runtime.lastError: This function must be called during a user gesture` in Chrome 133.
