### ISSUE TITLE
Screenity hangs when finishing recording after a recent update

### ISSUE THREAD

**Issue by ShuaiShao93** [alyssaxuu/screenity#220]
![Screenshot from 2024-02-22 20-13-42](https://github.com/alyssaxuu/screenity/assets/7556010/94f44dea-057a-4cdb-ae4f-4e962cd9e4d7)
It always hangs here after I finish the recording by clicking the red button. I can use "restore last recording" to find the recording tho.

**Comment by alyssaxuu** [comment]
I have had reports about it, I cannot reproduce what is happening though even with long recordings of over an hour, either on Mac or Windows. I could roll it back, however it was also causing issues before in some cases as well. Do you see any errors in the console? I will try to investigate and see if I can resolve it.

**Comment by ShuaiShao93** [comment]
> I have had reports about it, I cannot reproduce what is happening though even with long recordings of over an hour, either on Mac or Windows. I could roll it back, however it was also causing issues before in some cases as well. Do you see any errors in the console? I will try to investigate and see if I can resolve it.

For some reason, I can no longer reproduce this today. It's ok not to rollback it, since I can use  "restore last recording" anyway. FYI I'm using Ubuntu. I will share the console if I see it next time.

**Comment by alyssaxuu** [comment]
Appreciate it. I'm trying to see if it's caused by different recording configurations, or when recording a different window or screen, something that could prevent that page from receiving the recording data. One idea I had was to set some sort of timeout to detect if any data was received after a certain amount of time in the page, or a button to manually fetch it, although as a fallback if I can't figure out the source of the problem.

**Comment by ShuaiShao93** [comment]
> Appreciate it. I'm trying to see if it's caused by different recording configurations, or when recording a different window or screen, something that could prevent that page from receiving the recording data. One idea I had was to set some sort of timeout to detect if any data was received after a certain amount of time in the page, or a button to manually fetch it, although as a fallback if I can't figure out the source of the problem.

I got this again when I record a 1-hour long video. The duration might be the cause.

**Comment by alyssaxuu** [comment]
@ShuaiShao93 I have just made a new release that should hopefully solve this issue, and offer a way to recover the video in the editor page if it still happens to fail. It's [version 3.1.9](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.9), which is still under review on the Chrome Store, but should go live soon. Let me know if you still experience issues.

**Comment by alyssaxuu** [comment]
Should be live now!
