### ISSUE TITLE
z-index affecting other components from Radix

### ISSUE THREAD

**Issue by lidiagc** [alyssaxuu/screenity#222]
In our project, we are using several components from @radix-ui, such as the Dropdown Menu. When you open the dropdown menu, the div with content inside has the attribute `data-radix-popper-content-wrapper`.

We were facing an issue where certain teammates couldn't see the content of the dropdown when it was rendered in a modal, but other teammates could still see the dropdown. When inspecting the component, the teammates that could see the dropdown had this added to their styles:

```
[data-radix-popper-content-wrapper] { z-index: 999999999999!important; } 
```

We were very confused why some people had this extra styling and others didn't. Until we figured out that this small CSS was being added by the Screenity extension. Now we know that our Dropdown component needs to be updated to be rendered above modals, but the developer that was working on this didn't notice that this was an issue since for them the dropdown was visible.

Since this is an attribute that is widely used in the Radix components and could affect other projects, would it be possible to make this CSS rule more specific to the Screenity project?

Thank you

**Comment by alyssaxuu** [comment]
Sorry about that, just fixed it in the [latest release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.10). It should go live in the Chrome Store soon.

**Comment by oeyoews** [comment]
<img width="345" alt="image" src="https://github.com/alyssaxuu/screenity/assets/72405338/9510f16c-aeb2-448e-b8de-33f61aed5fbe">
I saw a question about z-index, not sure if it's relevant here, I can't change the resolution of the video @alyssaxuu

**Comment by alyssaxuu** [comment]
> <img alt="image" width="345" src="https://private-user-images.githubusercontent.com/72405338/317238535-9510f16c-aeb2-448e-b8de-33f61aed5fbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzAyNTgsIm5iZiI6MTcxMTYyOTk1OCwicGF0aCI6Ii83MjQwNTMzOC8zMTcyMzg1MzUtOTUxMGYxNmMtYWViMi00NDhlLWI4ZGUtMzNmNjFhZWQ1ZmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEyNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDhhNDNjNmNlMWYzYmVmOWZmZGFkYTkwY2UwNzcxMjZiNmI3MDgyNGQwMTY5MTliN2EwMDc3OTk0OTc4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0jziF9o8Lpqf4xz5ZNgiEcrtsyMUHKwRQOhKwoVPg_o"> I saw a question about z-index, not sure if it's relevant here, I can't change the resolution of the video @alyssaxuu

Oh no, I just noticed it. I've just submitted a new update in the Chrome Store with a fix for this, it might take a bit to go live. I will add the release here later today.
