### ISSUE TITLE
Webcam and toolbar not injected to other tabs when switching tabs.

### ISSUE THREAD

**Issue by adriennhem** [alyssaxuu/screenity#223]
When switching tabs I am getting the following error:

Error in event handler: TypeError: Cannot read properties of undefined (reading 'id')
    at chrome-extension://kbbdabhdfibnancpjfhlkhafgdilcnji/contentScript.bundle.js:66:153485

This seems to be preventing the injection of the toolbar and camera. If I refresh the tab I switched to then it will inject the camera and the toolbar.

**Comment by alyssaxuu** [comment]
Fixed in the [latest release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.10), it should go live in the Chrome Store soon!
