### ISSUE TITLE
[Information] Disable recorder

### ISSUE THREAD

**Issue by marcopollacci** [alyssaxuu/screenity#23]
Hi!
First, congratulations! I love this extension! And second i want to ask if it possible use this tools without necessarily having to record the screen, just only highlight mouse or similar :)

Thank you!

**Comment by alyssaxuu** [comment]
Hi, I suppose it would be possible, although the tool is a screen recorder first and foremost. Maybe I could create a separate extension for drawing only, maybe adding other tools like circles, rectangles, adding images and GIFs on top of the website, etc? Chrome is pretty strict about extensions being meant for one purpose, and mine is to record the screen, so it might not be a good idea to add that functionality into the tool.

**Comment by marcopollacci** [comment]
Oh i see! Thank you for quick response :)!!
