### ISSUE TITLE
一直显示

### ISSUE THREAD

**Issue by yishuijianghu** [alyssaxuu/screenity#238]
![1731634547499](https://github.com/user-attachments/assets/c4ef114d-50ec-47be-840b-01030931451c)
![Uploading 1731634547499.jpg…]()

**Comment by alyssaxuu** [comment]
Should be fixed in [version 3.1.12](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.12), it should go live soon in the Chrome Store. looks like it might have been caused by the latest version of Chrome.
