### ISSUE TITLE
Pen Size - Disappears on roll-over

### ISSUE THREAD

**Issue by histteacher** [alyssaxuu/screenity#24]
Awesome product!

Noticed that when the pen is selected, the resizing tool disappears when rolling off of the pen button and on to the resizing tool.
![Screenity](https://user-images.githubusercontent.com/38225776/100449595-3485d580-3082-11eb-9601-abe4cfec21d1.gif)

**Comment by alyssaxuu** [comment]
Just fixed the issue, thanks for reporting (version 2.3.2, might take some time to go live) :)
