### ISSUE TITLE
Change push to talk key binding

### ISSUE THREAD

**Issue by meandillar** [alyssaxuu/screenity#26]
**What:**
Current key binding for push-to-talk is `ctrl + m`, is it possible to change this to something like `option + m`?

**Why**
When I am trying to record some html form interaction like toggling a checkbox while using push-to-talk, the checkbox will not check/uncheck because I am holding the `ctrl` key.

**Comment by alyssaxuu** [comment]
I could look into that, I believe though I did try using the option key before and there was some issue with detecting the option + M keys at once. Ideally I'd let people pick the shortcut, but Chrome Extension shortcuts don't tell me if a key is being held, only when it's pressed. For the time being you could use the keyboard shortcut for muting/unmuting here: chrome://extensions/shortcuts which you can also customize.
