### ISSUE TITLE
Create and Switch Scenes 

### ISSUE THREAD

**Issue by Vad1mo** [alyssaxuu/screenity#28]
When recording a tutorial for example it is nice to have the option to create scenes and switch between the scenes during the recording. 

To start of a few common scenes can be hard-coded and would cover 80% of all the typical cases:

- Full Webcam view 
- Full Webcam view + the Desktop as a window.  
- Collection of scenes, where Webcam porthole and Desktop are preset to:
  - Center,
  - top-left, top-right, bottom-left, bottom-right, 
  - In size S, M, L

Assign shortcuts to the above scenes so the user who is recording can quickly switch between the scenes while recording.

Here is explainer for OBS, so you know what I am talking about https://www.youtube.com/watch?v=yfPRUElyZKI

**Comment by alyssaxuu** [comment]
That could be a pretty cool idea for sure! Full Webcam view is already available (camera only recording), switching between camera and desktop though would be a problem (even though I can switch video tracks by replacing them in the MediaRecorder, the camera stream has to be in a content script whereas the desktop stream is in the background, so it's not really possible to switch from one to the other.

I'm not sure what you mean by the preset - you can currently move the camera around wherever, but I cannot inject the camera in the desktop as it's bound to the browser. You'd need to use a small browser window and move it around yourself, or add it post-editing. This would be more of a feature for a potential native app, not for the Chrome Extension I think.

**Comment by Vad1mo** [comment]
I updated my question, so it is hopefully better to understand.  Wie preset I meant the scene with position of webcam on the screen and its size.

**Comment by alyssaxuu** [comment]
After reviewing it I decided this might be better off for a potential desktop version of Screenity, so out of scope for the extension. The reason is that the scenes functionality with the camera on top would be better suited to a tool that can inject that anywhere on your computer, not just Chrome, and able to switch between MediaRecorder streams (which isn't really possible in Chrome either). I will close this now.
