### ISSUE TITLE
I cannot activate the microphone or the Webcam

### ISSUE THREAD

**Issue by maiteyanguas** [alyssaxuu/screenity#29]
Hello, I have a very strange issue. It happens both in a W7 and in a W10 laptop. Most of the times, when I try to use the extension in Chrome, it doesn't appear the option to enable the microphone or the webcam and therefore I cannot use it. Sometimes it appears but most of the times not.

**Comment by alyssaxuu** [comment]
That is very strange. So the microphone and camera say "Disabled"? It might be due to specific websites preventing using your microphone and camera - can you share if that's the case (e.g. if there's particular websites where you have this issue)?

**Comment by maiteyanguas** [comment]
I'm sorry, I was always trying with the home page of the explorer (bing or google) and with those pages it doesn't work.

**Comment by alyssaxuu** [comment]
Ah yeah, unfortunately it's not able to inject scripts in those pages. I could try making it more clear though :)
