### ISSUE TITLE
Hiding recording of controls 

### ISSUE THREAD

**Issue by stevepixl8** [alyssaxuu/screenity#30]
Super easy to use, just wondering if there is a way to hide the controls from being seen in the final recording? The highlighting and other tools are really useful, but i don't really want end users seeing me selecting these while i'm recording.

**Comment by alyssaxuu** [comment]
Hi, unfortunately it is impossible to hide the controls in the screen as they are injected in the website, it'd have to be a standalone app. I had considered adding a bunch of keyboard shortcuts so you wouldn't need to use the controls at all, but there's a limit of 5 for Chrome Extensions, and I mapped those to the main actions (stopping, resuming, muting, etc.).

I'll close this as unless I work on a standalone version, there's nothing I can do about this.
