### ISSUE TITLE
Webcam hidden when clicking on presentation mode on google slides

### ISSUE THREAD

**Issue by theanandcom** [alyssaxuu/screenity#36]
The webcam seems to be moving behind the presentation when I click on the record button and make the presentation full screen.

**Comment by alyssaxuu** [comment]
I could look into it, but it might not be possible to inject content in fullscreen mode. And maybe I'd have to do it on a case by case scenario (Slides, Youtube, etc) if I have to inject the controls & camera inside a particular element (not sure how the fullscreen API works).

**Comment by alyssaxuu** [comment]
I looked into it and this is currently not possible. I might have plans for a desktop version which will allow for the camera and controls to always be on top of everything (including outside of Chrome), so that would be possible then :) Closing for now.
