### ISSUE TITLE
Screenity does not work in the desktop option

### ISSUE THREAD

**Issue by sirkif** [alyssaxuu/screenity#37]
Hi
First I appreciate your efforts.
I am trying to record my desktop ( Mac ), i clicked on it in the desktop option then share, but it doesn't work, in the Tab option, it works fine.

Best regards

Adam

**Comment by alyssaxuu** [comment]
Hi, this is likely just a permission setting on your device. Follow the instructions here to enable screen recording on Mac, and make sure Chrome is checked. You might have to restart the browser then: https://support.apple.com/guide/mac-help/control-access-to-screen-recording-on-mac-mchld6aa7d23/mac#:~:text=On%20your%20Mac%2C%20choose%20Apple,%26%20Privacy%2C%20then%20click%20Privacy.&text=Select%20Screen%20Recording.,it%20to%20record%20your%20screen.

**Comment by sirkif** [comment]
I found that the Camera and Microphone checkboxes are checked, and I think the problem is not with my Mac, because if that is the case, the Tab Only & Camera Only options won't work for me, but they work fine, only the desktop option doesn't work.

Thank you.

**Comment by alyssaxuu** [comment]
Oh I didn't mean Camera and Microphone, I meant Screen Recording :) And tab only + camera doesn't use the Screen Recording permission so that's why it still works for you.

<img width="632" alt="Screen Shot 2020-12-15 at 11 00 14 PM" src="https://user-images.githubusercontent.com/7581348/102277968-4e9c3080-3f29-11eb-8659-aa54e2d1a68a.png">

**Comment by sirkif** [comment]
It is working for me now. I appreciate your help. thanks.

Have a nice day.

**Comment by megaroeny** [comment]
Any idea what setting that would be for Windows? It's just black for my desktop recording, and I'm assuming it's a similar permission.
