### ISSUE TITLE
Circle cropping video with straight edge

### ISSUE THREAD

**Issue by BraydenGirard** [alyssaxuu/screenity#4]
There seems to be a small bug with how the video circle crops. See the screenshots attached.

![image](https://user-images.githubusercontent.com/3247657/99841383-1842df80-2b3c-11eb-8f01-5ca997d7546c.png)
![image](https://user-images.githubusercontent.com/3247657/99841469-36104480-2b3c-11eb-83f5-4b1dd43915de.png)

**Comment by alyssaxuu** [comment]
Hmm, is that only in the bigger sizes or all sizes?

**Comment by BraydenGirard** [comment]
All sizes

**Comment by alyssaxuu** [comment]
That is really strange. Can you do some troubleshooting? Use the extension again with the camera on, then go into Inspect Element in Chrome, scroll down to the div with the id="screenity-screen-recorder-extension", then "wrap-iframe", and then open the iframe, #document, html and body to reveal the "injected-video":

![image](https://user-images.githubusercontent.com/7581348/99842448-24489480-2b70-11eb-8101-6a800973fdab.png)

Then, with injected-video selected, can you add `transform: translateX(-50%) scale(.5);` to the style:

![image](https://user-images.githubusercontent.com/7581348/99842595-6d004d80-2b70-11eb-886a-5e8f38119c7c.png)

Then select the body tag:

![image](https://user-images.githubusercontent.com/7581348/99842770-bb155100-2b70-11eb-8678-a94d81900e5a.png)

And add `background: red;` into the style.

Then look at the camera and take a screenshot / just check if it looks off-center. I just want to check if the camera feed is centered with respect to the circle, or whether the dimensions are odd, or something else is broken (maybe a very unorthodox way to check but yeah haha).

**Comment by BraydenGirard** [comment]
![image](https://user-images.githubusercontent.com/3247657/99864379-f748b180-2b70-11eb-91db-ac451857d5e9.png)

**Comment by alyssaxuu** [comment]
Dang, that's a surprise. The video appears to be centered and the dimensions are certainly normal. I'll have to investigate further then, I'm really not sure why it's showing cut off in your case.

**Comment by BraydenGirard** [comment]
Is there something overlaying the video potentially?

**Comment by alyssaxuu** [comment]
Hmm nope, doesn't seem to be. I have another idea, can you try adding the following:

```
left: 50%;
top: 50%;
transform: translate(-50%, -50%);
```

to the #injected-video (same place as the first image I commented with) and uncheck the transform and unset properties? It's a different way to center the video, might work.

<img width="764" alt="Screen Shot 2020-11-21 at 3 11 54 PM" src="https://user-images.githubusercontent.com/7581348/99879249-e6994980-2c0b-11eb-923b-effc906d6bc5.png">

**Comment by BraydenGirard** [comment]
Hmm that didn't work but I also don't have an unset property. Also just so you know, the same issue is happening with my integrated webcam on my Lenovo X1 Extreme laptop as well as my Logitech StreamCam on my destkop PC.

**Comment by alyssaxuu** [comment]
Oops sorry, I meant inset. Just the same way it's in the image I put in the comment.

**Comment by willymerd** [comment]
what an amazing ext!

I just a reguler user from chrome extension,
I get same problem here

how to resolve it?

thanks

![Screenshot_3](https://user-images.githubusercontent.com/74842628/99890976-83ed8f80-2c97-11eb-8b1b-41a228a7d7dc.jpg)

**Comment by megaroeny** [comment]
I'm also experiencing this, on my windows 10 PC.

**Comment by alyssaxuu** [comment]
Agh. @willymerd @megaroeny Can you try doing what I described here: https://github.com/alyssaxuu/screenity/issues/4#issuecomment-731585079 and see if that fixes it? it's definitely very strange.

**Comment by Sameedahmad** [comment]
I added it from the #4 (comment) doesn't work.
<img width="960" alt="Screenshot 2020-11-22 143834" src="https://user-images.githubusercontent.com/53148681/99900304-93d59580-2cd0-11eb-8520-c3c8bfb146a4.png">

**Comment by Sameedahmad** [comment]
However, When the transform:translateX(-50%) and left:50% is unchecked, then it's not cutting off.

![image](https://user-images.githubusercontent.com/53148681/99900410-270ecb00-2cd1-11eb-9851-c9f883b51011.png)

**Comment by alyssaxuu** [comment]
Dang :( This appears to be a Windows issue then. I'm honestly not sure what's different from Mac, it's just really absurd. Getting rid of the left and transform properties simply makes the video off-center, but it's odd that it would show up fine in that case.

One thought I have is that the cut off section might actually be part of the video background & not actually the rest of the document underneath. Could you try setting the background-color property to another color (e.g. `background-color: red;`) to confirm in the #injected-video DIV (same place as previous comment)? It seems likely but at the same time it makes absolutely no sense for the video background to be visible when the video itself is playing. If it does change, try using `background-color: transparent;` and see if it goes away.

I'll keep looking into it, maybe there's an issue with the translate property in Windows, no idea though...

**Comment by Sameedahmad** [comment]
Nope, it's something else, Let's see!
![image](https://user-images.githubusercontent.com/53148681/99900772-5cb4b380-2cd3-11eb-8a61-c1d22d832b1b.png)

**Comment by alyssaxuu** [comment]
> Nope, it's something else, Let's see!
> ![image](https://user-images.githubusercontent.com/53148681/99900772-5cb4b380-2cd3-11eb-8a61-c1d22d832b1b.png)

All right, I think I got it, I believe that might be the iframe border. Can you select the iframe DIV for the camera and add `border: 0px!important`? Also inline in the iframe, add frameBorder="0", like this:

![image](https://user-images.githubusercontent.com/7581348/99900910-0d5e8b00-2cb3-11eb-963f-06e3ab426ae1.png)

**Comment by Sameedahmad** [comment]
It disappears!
<img width="829" alt="now 2" src="https://user-images.githubusercontent.com/53148681/99901214-c6828c80-2cd6-11eb-8f95-b0a853702327.png">

**Comment by alyssaxuu** [comment]
Hmm, and with border none? That's so odd the camera would disappear though... Maybe without the frameborder property?

**Comment by Sameedahmad** [comment]
Nothing happens with border none!

**Comment by alyssaxuu** [comment]
> Nothing happens with border none!

Hmm, what about adding `height: 100%` to the iframe and body inside the iframe?

**Comment by Sameedahmad** [comment]
That doesn't solve it either.

**Comment by megaroeny** [comment]
Sorry, haven't been home to help you debug. If there's anything else we can help you with, let us know.

BTW what browser specifically are people using? I know there are multiple chromium browsers that can use this extension. Myself, I'm using Edge v86.

Also - **I figured out a solution**! 😄 The reason why this is happening is because there is overflow. And unlike macOS, Windows always shows a scrollbar if there's overflow. Whereas in macOS (as you probably know), the scrollbar is more of an overlay and disappears when it's not scrolling.

See where I added `overflow: hidden`, on the `body` tag inside the `div#wrap-iframe > iframe`.

![image](https://user-images.githubusercontent.com/1559447/99914981-e8781100-2cce-11eb-81a2-30e8bf8329ef.png)

**Comment by alyssaxuu** [comment]
> Sorry, haven't been home to help you debug. If there's anything else we can help you with, let us know.
> 
> BTW what browser specifically are people using? I know there are multiple chromium browsers that can use this extension. Myself, I'm using Edge v87.
> 
> Also - **I figured out a solution**! 😄 The reason why this is happening is because there is overflow. And unlike macOS, Windows always shows a scrollbar if there's overflow. Whereas in macOS (as you probably know), the scrollbar is more of an overlay and disappears when it's not scrolling.
> 
> See where I added `overflow: hidden`, on the `body` tag inside the `div#wrap-iframe > iframe`.
> 
> ![image](https://user-images.githubusercontent.com/1559447/99914981-e8781100-2cce-11eb-81a2-30e8bf8329ef.png)

Oh amazing, I just added the change & it should go live in a few hours with the version 2.2.1. Thanks! :)

**Comment by megaroeny** [comment]
> Oh amazing, I just added the change & it should go live in a few hours with the version 2.2.1. Thanks! :)

Awesome! I was trying to find a way to target those elements inside the iframe, but I couldn't get it to find those elements. Curious - how/what did you do via your CSS?

**Comment by alyssaxuu** [comment]
> > Oh amazing, I just added the change & it should go live in a few hours with the version 2.2.1. Thanks! :)
> 
> Awesome! I was trying to find a way to target those elements inside the iframe, but I couldn't get it to find those elements. Curious - how/what did you do via your CSS?
> 
> For example, I was trying:
> 
> ```
> #screenity-screen-recorder-extension #wrap-iframe iframe body {
>    overflow: hidden;
> }
> ```
> 
> I see that your CSS rules have the `...-camera` suffix at the end of your classes, but didn't see that in the browser DOM 🤔

Well, the camera is injected via an iframe, the contents of which are in [this html file](https://github.com/alyssaxuu/screenity/blob/master/html/camera.html). I just added the style inline in that file :)

**Comment by Sameedahmad** [comment]
Thankyou @megaroeny @alyssaxuu That's great to know it has been fixed :)
