### ISSUE TITLE
Is it possible to integrate Screenity with my website without needing to install the extension version?

### ISSUE THREAD

**Issue by ismailxmuhammad** [alyssaxuu/screenity#42]
Hi @alyssaxuu,
What a great work you have accomplished! Many thanks for making it an opensource.
I would like to know if its possible to convert Screenity into a traditional web application that can be integrated with a website and do recording from within the website? Thanks in advance for any guidance.

**Comment by alyssaxuu** [comment]
Hi, yeah this is possible, only for desktop/camera recordings though. You'd have to basically remove everything Chrome-specific, it also would only add controls in your own site. A lot of work, but yeah you could do it :)
