### ISSUE TITLE
When I click on Google Drive nothing happens

### ISSUE THREAD

**Issue by mentzelia** [alyssaxuu/screenity#43]
Hi Alyssa,

I'm using Screenity (and by the way, it's a really nice app!) and I would like to use the Google Drive button to save the record but nothing happens.
What can I do ?

Thanks and have a nice day,

Virginia

**Comment by alyssaxuu** [comment]
Hi, the issue should be solved by either reinstalling the extension or if you're in the Brave browser, doing [this](https://github.com/alyssaxuu/screenity/issues/5#issuecomment-732303568). You can see in the thread other potential solutions depending on your browser.
