### ISSUE TITLE
How to support you?

### ISSUE THREAD

**Issue by sashage** [alyssaxuu/screenity#48]
Hi Alyssa,

is there a way to support you financially?

In a time where every tiny software or service is a SAAS nowadays, I really love to support independent developers who create quality products in the open-source space. You provide huge value here!

If you have something like buymeacoffee.com or so please let me know. I'd love to support you so you stick around and have an incentive to keep working on this and your other projects.

Thank you!

**Comment by alyssaxuu** [comment]
I really appreciate it - I have a [GitHub Sponsors account](https://github.com/sponsors/alyssaxuu?preview=true) where people can support my open source work :) It doesn't have to be recurring, I believe there is the option of making a one time payment (or cancelling right away too). Thanks!
