### ISSUE TITLE
Save to Drive is not working

### ISSUE THREAD

**Issue by nguyenrom** [alyssaxuu/screenity#5]
No thing happen when I click "Save to Drive". but "Download" is working good.

**Comment by alyssaxuu** [comment]
Hmm, do you not get a popup to sign in with Google? Maybe Chrome is blocking it - check in the URL bar if you see "popup blocked".

**Comment by nguyenrom** [comment]
Hi @alyssaxuu ,

I don't get any popup and notifications from Chrome, can you review my record: https://www.dropbox.com/s/xt2agpx432tt0mp/Screen%20Recording%202020-11-23%20at%2014.01.20.mov?dl=0

**Comment by Sebubu** [comment]
Just a side note (might be not priority #1):
Upload to Google Drive does not work with the Brave browser.

Console output:
```
nchecked runtime.lastError: The user turned off browser signing
```

**Comment by alyssaxuu** [comment]
> Just a side note (might be not priority #1):
> Upload to Google Drive does not work with the Brave browser.
> 
> Console output:
> 
> ```
> nchecked runtime.lastError: The user turned off browser signing
> ```

Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/

I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.

@nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.

**Comment by Sebubu** [comment]
I enabled the "Allow Google login for extensions" in the settings (disable by default) and now at least the Google Login page is opening. See video.

https://www.loom.com/share/13ec8c2b13344e66bd3da409fdc401e2

> > Just a side note (might be not priority #1):
> > Upload to Google Drive does not work with the Brave browser.
> > Console output:
> > ```
> > nchecked runtime.lastError: The user turned off browser signing
> > ```
> 
> Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/
> 
> I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.
> 
> @nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.

**Comment by alyssaxuu** [comment]
> I enabled the "Allow Google login for extensions" in the settings (disabled by default) and now at least the Google Login page is opening. See video.
> 
> https://www.loom.com/share/13ec8c2b13344e66bd3da409fdc401e2
> 
> > > Just a side note (might be not priority #1):
> > > Upload to Google Drive does not work with the Brave browser.
> > > Console output:
> > > ```
> > > nchecked runtime.lastError: The user turned off browser signing
> > > ```
> > 
> > 
> > Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/
> > I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.
> > @nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.

Huhh... The login page is supposed to show up as a popup, that might be causing some issues. I'll download the Brave browser and try it out myself to see what's going on, although looking online like I said it seems to be a common issue within the browser, so I'm not sure if it's so much on my end.

**Comment by nguyenrom** [comment]
> > I enabled the "Allow Google login for extensions" in the settings (disabled by default) and now at least the Google Login page is opening. See video.
> > https://www.loom.com/share/13ec8c2b13344e66bd3da409fdc401e2
> > > > Just a side note (might be not priority #1):
> > > > Upload to Google Drive does not work with the Brave browser.
> > > > Console output:
> > > > ```
> > > > nchecked runtime.lastError: The user turned off browser signing
> > > > ```
> > > 
> > > 
> > > Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/
> > > I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.
> > > @nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.
> 
> Huhh... The login page is supposed to show up as a popup, that might be causing some issues. I'll download the Brave browser and try it out myself to see what's going on, although looking online like I said it seems to be a common issue within the browser, so I'm not sure if it's so much on my end.

In my Edge browser - v87.0.664.41 (Official build) (64-bit) » The error in console is:
`Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-2).`

**Comment by alyssaxuu** [comment]
> > > I enabled the "Allow Google login for extensions" in the settings (disabled by default) and now at least the Google Login page is opening. See video.
> > > https://www.loom.com/share/13ec8c2b13344e66bd3da409fdc401e2
> > > > > Just a side note (might be not priority #1):
> > > > > Upload to Google Drive does not work with the Brave browser.
> > > > > Console output:
> > > > > ```
> > > > > nchecked runtime.lastError: The user turned off browser signing
> > > > > ```
> > > > 
> > > > 
> > > > Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/
> > > > I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.
> > > > @nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.
> > 
> > 
> > Huhh... The login page is supposed to show up as a popup, that might be causing some issues. I'll download the Brave browser and try it out myself to see what's going on, although looking online like I said it seems to be a common issue within the browser, so I'm not sure if it's so much on my end.
> 
> In my Edge browser - v87.0.664.41 (Official build) (64-bit) » The error in console is:
> `Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-2).`

Ah I see, I just looked it up and found [this](https://jasonsavard.com/forum/discussion/6055/oauth2-request-failed), it should be solved by reinstalling the extension :)

**Comment by alyssaxuu** [comment]
> I enabled the "Allow Google login for extensions" in the settings (disabled by default) and now at least the Google Login page is opening. See video.
> 
> https://www.loom.com/share/13ec8c2b13344e66bd3da409fdc401e2
> 
> > > Just a side note (might be not priority #1):
> > > Upload to Google Drive does not work with the Brave browser.
> > > Console output:
> > > ```
> > > nchecked runtime.lastError: The user turned off browser signing
> > > ```
> > 
> > 
> > Oh I see, so the issue might be with a setting set by the user where it prevents the sign in prompt from showing. Not sure where this is set though - I see this: https://www.techjunkie.com/chrome-auto-sign-in/
> > I looked up for the issue in the Brave browser and it seems to be a bug? Lots of people mention being unable to sign in with Google in apps and extensions. It says though to make sure "Allow Google login for extensions" is enabled in the settings.
> > @nguyenrom can you share what you get in the console in inspect element when you click on the Save to Drive button? Might be a similar issue in Edge.

Ok, I found the fix. Go into the Brave browser settings and set it to "Allow all cookies" for the shields. Should work fine, a new tab will open to sign in and then a Google Drive tab will open afterwards with the video.

**Comment by Sebubu** [comment]
@alyssaxuu Maybe I misunderstood your solution but are you saying we should disable our third-party cookie blocker for all websites? Doesn't feel like the perfect solution.

**Comment by alyssaxuu** [comment]
> @alyssaxuu Maybe I misunderstood your solution but are you saying we should disable our third-party cookie blocker for all websites? Doesn't feel like the perfect solution.

Yes, unfortunately there's no other option for Chrome Extensions. If you do a search on the topic (Google Sign in for Chrome Extensions in the Brave browser) the only solution so far is to disable the cookie blocker. I can't change the sign in process, extensions are supposed to do it a certain way in order to get access to the API to upload the video to Drive, so there really is nothing for me to do in the matter.

**Comment by megaroeny** [comment]
I'm having this issue as well with MS Edge v87 (Chrome version). I can't find a similar setting to the one mentioned. Any ideas?

**Comment by alyssaxuu** [comment]
> I'm having this issue as well with MS Edge v87 (Chrome version). I can't find a similar setting to the one mentioned. Any ideas?

Apparently to fix the issue you have to reinstall the extension (based on what I read online about the specific error that gets logged).

**Comment by megaroeny** [comment]
> > I'm having this issue as well with MS Edge v87 (Chrome version). I can't find a similar setting to the one mentioned. Any ideas?
> 
> Apparently to fix the issue you have to reinstall the extension (based on what I read online about the specific error that gets logged).

That didn't work 😕

**Comment by alyssaxuu** [comment]
> > > I'm having this issue as well with MS Edge v87 (Chrome version). I can't find a similar setting to the one mentioned. Any ideas?
> > 
> > 
> > Apparently to fix the issue you have to reinstall the extension (based on what I read online about the specific error that gets logged).
> 
> That didn't work 😕

Odd, do you get the `Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-2).` error in your console? Or another kind of error?

**Comment by megaroeny** [comment]
Yup, I do, plus another warning:
![image](https://user-images.githubusercontent.com/1559447/100165761-0f7a4280-2e89-11eb-9e7b-eea58e5e66f2.png)

**Comment by alyssaxuu** [comment]
> Yup, I do, plus another warning:
> ![image](https://user-images.githubusercontent.com/1559447/100165761-0f7a4280-2e89-11eb-9e7b-eea58e5e66f2.png)

Dang. [This](https://jasonsavard.com/forum/discussion/6055/oauth2-request-failed) is the only mention of that specific error I could find, and it just mentions possibly having to do with a delayed Internet connection, or maybe some conflict with some other extension, and it's also having to do with Edge. I'm really not sure what it could be, maybe some sort of setting preventing the OAuth modal showing up for "security reasons", but I just can't find any information on it on the documentation for Google OAuth or anywhere.

**Comment by megaroeny** [comment]
> > Yup, I do, plus another warning:
> > ![image](https://user-images.githubusercontent.com/1559447/100165761-0f7a4280-2e89-11eb-9e7b-eea58e5e66f2.png)
> 
> Dang. [This](https://jasonsavard.com/forum/discussion/6055/oauth2-request-failed) is the only mention of that specific error I could find, and it just mentions possibly having to do with a delayed Internet connection, or maybe some conflict with some other extension, and it's also having to do with Edge. I'm really not sure what it could be, maybe some sort of setting preventing the OAuth modal showing up for "security reasons", but I just can't find any information on it on the documentation for Google OAuth or anywhere.

I can play around with my security settings, and also disable other extensions to try and troubleshoot. 🙂 I do have strict security settings on, but normally I can whitelist a site. In this case, I don't see how to do that since it's an extension and it treats the URL differently.

**Comment by megaroeny** [comment]
Well shucks, I used the lowest security setting and turned off all other extensions, and same error. Wonder if it's a limitation of Edge currently. What that limitation is, I don't know.

**Comment by nguyenrom** [comment]
Case 1, there was no error message: 
I have installed Screenity in a new Edge browser:
https://www.loom.com/share/94dacbaad2a64abbb2451314bf5e534e

Case 2, in primary browser with many Chrome extensions:
`Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-2).`
