### ISSUE TITLE
How to improve vedio quality

### ISSUE THREAD

**Issue by abhinav-TB** [alyssaxuu/screenity#50]
Is there any way to improve the video quality and the recording screen dimension

**Comment by alyssaxuu** [comment]
Screenity takes the resolution of your browser (the size it's currently at, so if you resize it the resolution will change) for tab recordings, and the resolution of your screen for desktop recordings, so there's that limit. I could look into how to improve video quality though nonetheless, maybe some parameters when starting the recording could help.

**Comment by abhinav-TB** [comment]
ok thx, just one more thing, why is the camera on while the recording is starting with camera disabled

**Comment by alyssaxuu** [comment]
The camera shouldn't be on if you set it as disabled. You can block Screenity from using your camera to be sure (when you open the popup, click on the icon on the right side of the address bar and deny permission to the camera), but yes, it shouldn't activate. What might happen is that Screenity checks your preferences when starting the recording, and it also gathers information about your camera devices were you to activate your camera during your recording.

**Comment by abhinav-TB** [comment]
The light in my camera is on even when it is disabled that means the extension has access to it even though it is not recording a video, it raises privacy concerns

**Comment by alyssaxuu** [comment]
> The light in my camera is on even when it is disabled that means the extension has access to it even though it is not recording a video, it raises privacy concerns

Hmm I see, I will look into that, seems odd that the light would be on for sure.

**Comment by charitarthchugh** [comment]
I experience the same camera issue.
