### ISSUE TITLE
Error: Can't record in this page

### ISSUE THREAD

**Issue by jeffreyoelen** [alyssaxuu/screenity#52]
Hi, 

I want to use the extension, but get the following error in every screen I have open on my computer. 
'Can't record in this page'. 
This happens when I want to use Tab Only, Desktop and Camera Only. 

The extension cannot find my camera and microphone. 

I am using a Windows 10 laptop and have installed Chrome version 88.0.4324.104

Hopefully you can help me out. 

Cheers, Jeffrey

**Comment by alyssaxuu** [comment]
That's because Screenity can't record in new tab pages, the Chrome Store, or an internal Chrome page. Try going to another website and recording from there :)

**Comment by jeffreyoelen** [comment]
Hi Alyssaxuu, 

Thanks, its working now! :)
