### ISSUE TITLE
Chrome crashes after recording camera fullscreen

### ISSUE THREAD

**Issue by awrog** [alyssaxuu/screenity#53]
I love this addon! There is only one problem with it, recoding camera only.
Steps to reproduce the problem:
- I record camera only
- I pause the recording and want to save it (clicking green check)
- Google Chrome (88.0.4324.104 (Official Build) (64-bit)) crashes and the recording is gone

When recording the screen with camera, everything works great!

**Comment by alyssaxuu** [comment]
Oh wow, I just updated Chrome and indeed it does crash when doing a camera only recording! I need to see what's going on with this new version of Chrome.

**Comment by alyssaxuu** [comment]
All right, so apparently using window.open() without the windowName parameter was crashing it, really odd. I added target _blank and it fixed it, will be live in version 2.6.0 which I've just submitted for review. For the time being (might take a while to go live) you can self-host the version here on GitHub which is up to date, following the guide in the README.
