### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by liuxgchi** [alyssaxuu/screenity#54]
![image](https://user-images.githubusercontent.com/7333031/106294783-903f2b80-628a-11eb-9389-f00b1d37e5f1.png)
it is always showed lick the photo above, it can not get the microphone and camera 's permission, and can not start to work ,my pc is a  mac pro

**Comment by alyssaxuu** [comment]
Hi, this is because the extension can't record in the page that you're currently on (Google homepage, new tab page, or an internal browser page). Try going to another website and opening the popup again (that's why the button is disabled in the bottom).

**Comment by liuxgchi** [comment]
Thank you! It work well like you say.But I have another question. the function that Annotate by drawing anywhere on the screen, adding text, and creating arrows can not work, It has ever show in my screen.

**Comment by alyssaxuu** [comment]
> Thank you! It work well like you say.But I have another question. the function that Annotate by drawing anywhere on the screen, adding text, and creating arrows can not work, It has ever show in my screen.

That's odd - have you clicked on the pencil icon in the toolbar in the bottom left? It should open the tools to annotate.

**Comment by liuxgchi** [comment]
Thank you ,I found it when the mouse scroll into that area.
