### ISSUE TITLE
Unable to record desktop

### ISSUE THREAD

**Issue by haresrv** [alyssaxuu/screenity#59]
Hi Alyssa, 
Thank you for the amazing project. I'm using it in Ubuntu 16.04 and Chrome browser. I'm able to record tabs properly but when I try recording desktop, it starts and stops within seconds. When I enabled error collection, I found the following error

Uncaught (in promise) InvalidStateError: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track

Would you know what likely would have caused this issue?

**Comment by alyssaxuu** [comment]
Hi, yes, this is something I will fix in the next build. You just have to make sure "Share audio" is checked when you start a desktop recording for now, otherwise it will crash.
