### ISSUE TITLE
Add Option for Custom Recordable Area

### ISSUE THREAD

**Issue by LeonnardoVerol** [alyssaxuu/screenity#6]
Add Option for Custom Recordable Area, instead of fullscreen only

**Comment by alyssaxuu** [comment]
I think that should be possible, I'd just have to see how to make it work with the current setup (as ATM there's tab, desktop, and camera recordings & no more space, + how it would work together with the controls & camera embed).

**Comment by prashant-shahi** [comment]
Hey @alyssaxuu, I was wondering how do you think we can approach to record a specific area of the screen. I might be able to spend some time delivering this feature.

**Comment by alyssaxuu** [comment]
Added in the MV3 version, along with cropping in the editor.
