### ISSUE TITLE
Recording styles and functionality issues

### ISSUE THREAD

**Issue by pavaniappit** [alyssaxuu/screenity#60]
Getting below issues while recording

browser :  Chrome
browser version: 88.0.4324.150 (Official Build) (64-bit)
Os : Windows 10

1. Cursor settings, Annonation tools and recording settings are not working 
2. Color picker is adding below the webpage with some white space above it and page is getting scrolled
3. Camera is in square shape not in circular shape
![image12](https://user-images.githubusercontent.com/77262586/107762972-d6e55900-6d53-11eb-963d-5e1ec6e5e047.PNG)
![image1](https://user-images.githubusercontent.com/77262586/107762977-d8168600-6d53-11eb-91c5-555526842d81.PNG)

Thanks & Regards,
Pavani Sahukari

**Comment by alyssaxuu** [comment]
Hmm that's strange. Are you using a self-hosted version of Screenity (the code on GitHub) or the version in the Chrome Store? I tried recording in the same page using the extension in the Chrome Store and it works just fine in terms of styling. I will look into it nonetheless, if you're using it through GitHub there might be some disparity causing the issue.

**Comment by alyssaxuu** [comment]
Ah I see yes, the development version had some disparities with the production one. I have just pushed a fix for it, the styling issues should be gone :)
