### ISSUE TITLE
make the annotations anchor at a place as we scroll

### ISSUE THREAD

**Issue by gurrrung** [alyssaxuu/screenity#63]
Currently, scrolling keeps the annotations at the fixed position. It should move with the scrolling page.

**Comment by alyssaxuu** [comment]
Hmm, maybe there could be the option for this, but a main use case of the annotations is to give feedback on a website (e.g. article, landing page, webapp) so you can scroll down and keep it there. Not sure how common of a request this is for it to be the default (most users I talk to use it within their company for reviews, bug reports, etc where the annotation being scrollable is important).

**Comment by gurrrung** [comment]
I think since screenity is a screen recording tool, making it scrollable along with the webpage makes more sense.
