### ISSUE TITLE
add option to add shortcut for `Clear` button

### ISSUE THREAD

**Issue by gurrrung** [alyssaxuu/screenity#64]
Since the clear button is highly usable. Making it possible to add shortcut key for clearing all the annotation with the press of key combinations would be useful

**Comment by alyssaxuu** [comment]
I'd like to add a shortcut for it, but Chrome Extensions have a limit of 4 shortcuts (chrome://extensions/shortcuts) which I'm using for Pause/Resume, Stop, Cancel, and Mute/Unmute. I could assign a keystroke to clear the annotations regardless, but this can be conflicting depending on the website (if they're using shortcuts for something else), and it wouldn't be customizable.
