### ISSUE TITLE
QUESTIONS: Is there a time limit, and where can I access previous recordings?

### ISSUE THREAD

**Issue by candideu** [alyssaxuu/screenity#66]
As the title indicates: is there a maximum duration for recordings? Also, where can I find my previous recordings?

**Comment by willkxx2** [comment]
Unsubscribe

**Comment by alyssaxuu** [comment]
There is no time limit for recordings. Because this tool has no servers, your recordings aren't saved anywhere until you download them to your computer.

**Comment by willkxx2** [comment]
Who are you
