### ISSUE TITLE
Chrome crashes when recording video with full screen

### ISSUE THREAD

**Issue by Anil-matcha** [alyssaxuu/screenity#67]
Hi @alyssaxuu,

The chrome extension works great for most of the time but it crashes when recording "Camera only" videos similar to mentioned here https://github.com/alyssaxuu/screenity/issues/53 . This happens only with "Camera only" and not with Tab only/Desktop . 

I have tried using the self-hosted version from README but even there the issue seems to be the same. Can you kindly let me know what needs to be done for this ?

**Comment by Anil-matcha** [comment]
I was trying to look at what issue might be causing this. There is a response from someone mentioning window.open will create a tab in the same process which could relate to a crash, so I tried adding "noreferrer" like below to camera.js

newwindow = window.open('../html/videoeditor.html', "_blank", 'noreferrer'); 

Now chrome is not crashing, but the recordedBlobs are not getting passed to the opened tab and hence the video is empty

**Comment by Anil-matcha** [comment]
Hi @alyssaxuu . I have tried updating my chrome version to latest Version 89.0.4389.82 . Now the crash is gone but when trying to record with camera full screen, the videoeditor screen never comes up. The screen just stops recording and no output is generated. My OS is windows 10 .

**Comment by Anil-matcha** [comment]
Hi @alyssaxuu . I guess I understood the issue. When the recording is supposed to be stopped when clicked on save from "Camera-only" there is a race condition due to the stop-save message sent to scripts background.js and camera.js . Because of this, the camera screen is removed even before the popup to videoeditor is called and hence the recorded video is not generated.

If we can first generate the video and then send back a message to background.js to remove the injected code, it should be working good

**Comment by alyssaxuu** [comment]
Just looked into it and fixed it, it should go live soon :) Feel free to self-host the version on GitHub for the time being. Thanks for troubleshooting!
