### ISSUE TITLE
[FR] Add ability to mute the tab being recorded (but still record the audio)

### ISSUE THREAD

**Issue by NightMachinary** [alyssaxuu/screenity#70]
This feature is needed when one wants to record, e.g., a class but doesn't want to hear it now.

**Comment by alyssaxuu** [comment]
That's easy to implement, would just need to remove [this line](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/background.js#L190) that keeps the audio playing. Just unsure how to surface that in the UI.

**Comment by NightMachinary** [comment]
[**@alyssaxuu**](https://github.com/alyssaxuu) commented on [Mar 16, 2021, 4:31 PM GMT+3:30](https://github.com/alyssaxuu/screenity/issues/70#issuecomment-800238453 "2021-03-16T13:01:11Z - Replied by Github Reply Comments"):
> That's easy to implement, would just need to remove [this line](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/background.js#L190) that keeps the audio playing. Just unsure how to surface that in the UI.

Can you just respect the page's own mute setting? If the page is muted, do not play the sound. Currently, starting recording breaks the native mute option.

**Comment by alyssaxuu** [comment]
Hmm, it appears there's a way to check for that through an extension: https://developer.chrome.com/docs/extensions/reference/tabs/#type-MutedInfo

Might look into it.

**Comment by alyssaxuu** [comment]
Closing this one as there's a dedicated issue for it in #78.
