### ISSUE TITLE
[FR] Fix videos' seekability 

### ISSUE THREAD

**Issue by NightMachinary** [alyssaxuu/screenity#71]
You can do this using, e.g., `ffmpeg -err_detect ignore_err -i "$input" -c copy "$outpt"`.

**Comment by alyssaxuu** [comment]
I can't use FFMPEG here because it doesn't support the audio format for WEBM on the client. I can only use it to convert to GIF.

**Comment by NightMachinary** [comment]
@alyssaxuu Why are files saved as unseekable `webm` files in the first place? (Just curious, as all recording extensions share this bug)
