### ISSUE TITLE
Issues on Edge Chromium 

### ISSUE THREAD

**Issue by stijnhurkmans** [alyssaxuu/screenity#72]
Any reason why this shouldn't work on Edge Chromium (v89.0.774.54)? I've  tried it from the store and locally but only managed to get it working a few times but it keeps getting stuck on "loading" where it should say "start recording". It looks promissing and would be a great help to our non-profit organisation!! 

Errors:
Unchecked runtime.lastError: Cannot access chrome:// and edge:// URLs

Context

extension://kbbdabhdfibnancpjfhlkhafgdilcnji/_generated_background_page.html

Stack-trace

_generated_background_page.html:0 (anonieme functie)

**Comment by alyssaxuu** [comment]
Hmmm are you trying to run the extension from an edge:// URL? I only check for chrome:// and other internal URLs since it's meant to be a Chrome extension, but I could add edge:// as another blocked URL. It should be working fine though for recording in any other page.

**Comment by stijnhurkmans** [comment]
Indeed! I ran the extension on a blank tab in Edge because I needed to capture Outlook in this case. I didn't realise there was an URL check.
