### ISSUE TITLE
Mute Site setting is not respected

### ISSUE THREAD

**Issue by vwkd** [alyssaxuu/screenity#78]
Hi, first of all, thanks a lot for this amazing screen recorder! ❤️

I noticed, that with Screenity enabled, the Mute Site setting of the tab doesn't work anymore and you continue to hear the audio even if you muted the tab. Is this expected behavior?

I'd like to record a Web page with audio but not audible through the computer audio. This allows me to do other things in other tabs while the recording takes place in the background.

Steps to reproduce:
1. Open a web page with sound, like a YouTube video
2. Enable Screenity for the tab
3. Enable Mute Site for the tab
4. Notice, how you continue to hear audio from that tab.
5. (Notice, how you continue to hear audio even if you disable browser audio in the Screenity menu)

**Comment by alyssaxuu** [comment]
Fixed in 2.7.4.

**Comment by the-anonymous-raven** [comment]
Actually I am facing the same issue. I am on the latest version 2.7.4 and :
a. when I have a muted tab and start recording,  audio starts playing via speakers/earphones.
b. when I start recording on unmuted tab and then, press 'mute tab' option, audio does not get muted.

**Comment by NightMachinery** [comment]
@alyssaxuu Can you take a look at this? Unmuting via the overlay button at the bottom does not work (the audio plays and is recorded). Unmuting by right-clicking the tab also does nothing.
