### ISSUE TITLE
If I'm going to record with Camera Only mode, after recording complete It's not navigating to video editor screen most time

### ISSUE THREAD

**Issue by praveen-ui-dev** [alyssaxuu/screenity#81]

**Comment by alyssaxuu** [comment]
Fixed in 2.7.4 :)

**Comment by praveen-ui-dev** [comment]
I have tested it plenty of times but getting same issue

**Comment by praveen-ui-dev** [comment]
> I have tested it plenty of times but getting same issue



> Fixed in 2.7.4 :)

I have tested it plenty of times but getting same issue
