### ISSUE TITLE
Missing media metadata when exporting videos

### ISSUE THREAD

**Issue by RohitRajP** [alyssaxuu/screenity#82]
Maybe I am doing something wrong, but the exported video after recording seems to be missing metadata.

This is the metadata of the file exported from the extension (.mp4) ![image](https://user-images.githubusercontent.com/44432182/115816483-8c005580-a416-11eb-9ee8-51a5491cbcad.png)

I then ran the same file through a video converter, which then attached the required metadata for the video file:
![image](https://user-images.githubusercontent.com/44432182/115816715-f913eb00-a416-11eb-8970-f6640780b1cd.png)

This metadata is required, cause when uploading the file to platforms such as Whatsapp, due to the lack of metadata, it is being uploaded as a file, instead of a media document.

Is this a mistake on my side or something that needs a PR?

Otherwise the extension is top notch. Thanks!

**Comment by praveen-ui-dev** [comment]
Same issue I'm facing, recorded video isn't working in Mac or in any app.

**Comment by alyssaxuu** [comment]
Same issue as #7, nothing I can do unless Chrome fixes a bug which leads to missing metadata when generating videos, or I pay $$$ for servers to process the video which makes absolutely no sense for a free and open source extension. Closing this one to keep the discussion there.

**Comment by hanashiro** [comment]
@alyssaxuu I fixed this problem on my screen recorder using the package [fix-webm-duration](https://www.npmjs.com/package/fix-webm-duration)

My Recorder: [MemoPlay](https://github.com/mewters/memoplay-screen-recorder)

**Comment by alyssaxuu** [comment]
@hanashiro Hm, this only works for webm files though, not mp4? Still might look into it if it fixes issues with the webm format. Thanks!
