### ISSUE TITLE
Unable to mute running audio while recording

### ISSUE THREAD

**Issue by the-anonymous-raven** [alyssaxuu/screenity#83]
I'm on version 2.7.4 of the extension on Chrome. I'm facing this issue:
a. If the tab is muted, then pressing the record button enables the audio.
b. If the tab is unmuted, then while recording even if I mute the tab, I can still hear the audio.

Seeing one of the issues raised, I guess some part work has been done in this.
It is quite distracting to work in other tabs if sound from a (recording) tab is continuously on.

**Comment by alyssaxuu** [comment]
Should be fixed now.
