### ISSUE TITLE
Publish your extension to Microsoft Edge Addons website

### ISSUE THREAD

**Issue by nagachaitanyalokam** [alyssaxuu/screenity#84]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by alyssaxuu** [comment]
Perfect, I just submitted the extension to Edge after making the changes, will let you know when it goes live :)

**Comment by alyssaxuu** [comment]
It's live! :) https://microsoftedge.microsoft.com/addons/detail/screenity-screen-record/nbdkgeeeabnfegekngimpknhnkmocjcj

**Comment by alyssaxuu** [comment]
> There doesn't seem to be an update.

At the moment I am prioritizing Chrome, so I can make sure it is completely stable and compatible across devices. I will then work on rolling out the new version on Edge (which will require additional testing, and probably some changes to the code as well).
