### ISSUE TITLE
"save to Drive" saves low resolution video

### ISSUE THREAD

**Issue by edjusted** [alyssaxuu/screenity#87]
If I download the video, I get the full-resolution video, which I can of course then save to my Google Drive.

But if I choose the direct "save to Drive" option, I get a 360p resolution video.

Is there a way to fix/adjust this?

**Comment by erickvils** [comment]
I think this is a behavior of Google Drive for recent uploaded videos.  

Did you try to access  1 hour later to check if full resolution is available?

**Comment by edjusted** [comment]
Hmm, now I can't reproduce it. I don't believe this is a Google Drive issue. The way I determined the file was 360p was I downloaded it and opened it in VLC, so I bypassed Google's own video viewer.

I know for sure this happened before because I made a recording, then after saving it, noticed that it was only 360p so I had to re-do it. I'll keep an eye out and see if I can reproduce it again.

**Comment by alyssaxuu** [comment]
Hmm that's odd. I have experienced quality issues sometimes when saving to Drive, same as when uploading to Youtube where it only shows lower resolutions until some time later. Either way it's not something I would have any power over, I am using the [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API) which is pretty straightforward, so if anything it would be an issue with the API itself. I am simply passing the mimeType [in the background script](https://github.com/alyssaxuu/screenity/blob/935ea64aab0fa16d1c7e603117e9f118e529e234/js/background.js#L65) and it starts recording based off that, for lower resolutions I simply specify a low bitrate (which you can toggle from the 3 dots menu in the popup).

But yeah, I'm closing as I don't think it's something I can have any control over in the code.
