### ISSUE TITLE
Annotations don't work with touch events

### ISSUE THREAD

**Issue by Jivings** [alyssaxuu/screenity#9]
Love the extension! 

Would be awesome if the annotations worked with my touchscreen as well as my mouse.

**Comment by alyssaxuu** [comment]
Just added touchscreen support - might take a few hours to update in the Chrome Store (version 2.2.0).

**Comment by Jivings** [comment]
Wow, nice work! 15 minutes from ticket to launch! 👍

**Comment by alyssaxuu** [comment]
@Jivings Changes just went live :)
