### ISSUE TITLE
[Demo] Making the recorded video immediately available.

### ISSUE THREAD

**Issue by rahulbansal16** [alyssaxuu/screenity#95]
Thanks, @alyssaxuu for such an amazing project and for allowing others developers to build on top of it.

I have made code changes to immediately upload the video to the s3 bucket and anyone can spin up the infra immediately as it uses the lambda functions on the serverless framework.

You can take a look at the demo here https://app.orso.live/
If you want to try it for yourself. You can use the my version of extension https://github.com/rahulbansal16/screenity

I am planning to open source the project and will launch it on the product hunt. 
@alyssaxuu can you help me with the launch? I understand you are busy with your day-to-day work.

The demo video does not support seek till half of the video is downloaded.
I am planning to hack it by sending the metadata in the WebM format early.
Do you have ideas to tackle the seek issue?

**Comment by rahulbansal16** [comment]
@alyssaxuu can you publish the justification for the Permission for publishing the extension on the chrome store. It will help other developers trying to build and publish the app.

**Comment by alyssaxuu** [comment]
I am closing this as I am taking a different direction in regards to making the video immediately available.
