### ISSUE TITLE
Use MKV container instead of WebM and Mp4

### ISSUE THREAD

**Issue by Cyberavater** [alyssaxuu/screenity#96]
It seems, both in WebM and Mp4 format the video progress bar is not manually changeable (both in VLC and MPV player).
So, what did was, changed the container to MKV, and the video progress bar is now manually changeable. So, I'd request you to use the MKV container or at least add it as an option. Thanks!

**Comment by rahulbansal16** [comment]
Hey @Cyberavater  the issue was that chrome does not create the metadata for the webm files. I have made a fix you can refer to it.

**Comment by Cyberavater** [comment]
> Hey @Cyberavater the issue was that chrome does not create the metadata for the webm files. I have made a fix you can refer to it.

Eh? Can you link me to the fix?

**Comment by itsmeboy0** [comment]
After looking at his fork, I believe it's this one https://github.com/rahulbansal16/screenity/tree/rabans/rolling

@rahulbansal16 Can you create a PR for this?

**Comment by rahulbansal16** [comment]
hey @itsmeboy0  sure I will create the PR once I find time, currently busy with some project.

**Comment by alyssaxuu** [comment]
Fixed video encoding in the new MV3 version.
