### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by rakleed** [alyssaxuu/screenity#99]
It would be nice if you made a Safari extension. Since starting with version 14, support for the WebExtensions API has appeared. And from version 15 there will be support for Safari for iOS. More details: https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by alyssaxuu** [comment]
Could be nice, I think I will focus on the Chrome version though for the time being.

**Comment by alyssaxuu** [comment]
Closing as I don't really have plans for the Safari extension, it would add additional workload and issues supporting the browser and making it compatible. I'm prioritizing a native desktop app that has more functionality and can be used by more users.
